import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'th'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// English translations
const en: Record<string, string> = {
  // App - Sidebar Menu
  "menu.tuitionManagement": "Tuition Management",
  "menu.dashboard": "Dashboard",
  "menu.termSettings": "Term Settings",
  "menu.debtReminder": "Debt Reminder",
  "menu.paymentHistory": "Payment History",
  "menu.transactions": "Transactions",
  "menu.afterSchool": "After School",
  "menu.registrationSettings": "Registration Settings",
  "menu.courses": "Courses",
  "menu.externalParents": "External Parents",
  "menu.receipts": "Receipts",
  "menu.eventManagement": "Event Management",
  "menu.eventImport": "Event Import",
  "menu.paymentDeadlines": "Payment Deadlines",
  "menu.registrationReports": "Registration Reports",
  "menu.summerActivities": "Summer Activities",
  "menu.import": "Import",
  "menu.registrationControl": "Registration Control",
  "menu.paymentReports": "Payment Reports",
  "menu.discountManagement": "Discount Management",
  "menu.overview": "Overview",
  "menu.studentGroups": "Student Groups",
  "menu.promotions": "Promotions",
  "menu.waiveFees": "Waive Fees",
  "menu.reports": "Reports",
  "menu.invoiceManagement": "Invoice Management",
  "menu.invoices": "Invoices",
  "menu.itemsTemplates": "Items / Templates",
  "menu.emailJobs": "Email Jobs",
  "menu.studentList": "Student List",
  "menu.tuitionByYear": "Tuition by Year",
  "menu.users": "Users",
  "menu.rolesPermissions": "Roles & Permissions",
  "menu.familyGroups": "Family Group",
  "menu.studentManagement": "Student Management",
  "menu.userManagement": "User Management",

  // Common
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.add": "Add",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.export": "Export",
  "common.import": "Import",
  "common.view": "View",
  "common.close": "Close",
  "common.confirm": "Confirm",
  "common.back": "Back",
  "common.next": "Next",
  "common.submit": "Submit",
  "common.reset": "Reset",
  "common.loading": "Loading...",
  "common.noData": "No data available",
  "common.all": "All",
  "common.status": "Status",
  "common.academicYear": "Academic Year",
  "common.allAcademicYears": "All Academic Years",
  "common.actions": "Actions",
  "common.total": "Total",
  "common.amount": "Amount",
  "common.date": "Date",
  "common.name": "Name",
  "common.email": "Email",
  "common.phone": "Phone",
  "common.address": "Address",
  "common.description": "Description",
  "common.notes": "Notes",
  "common.type": "Type",
  "common.yes": "Yes",
  "common.no": "No",
  "common.required": "Required",
  "common.optional": "Optional",
  "common.select": "Select",
  "common.selectAll": "Select All",
  "common.clear": "Clear",
  "common.clearFilters": "Clear Filters",
  "common.refresh": "Refresh",
  "common.print": "Print",
  "common.download": "Download",
  "common.upload": "Upload",
  "common.send": "Send",
  "common.approve": "Approve",
  "common.reject": "Reject",
  "common.pending": "Pending",
  "common.approved": "Approved",
  "common.rejected": "Rejected",
  "common.draft": "Draft",
  "common.sent": "Sent",
  "common.paid": "Paid",
  "common.unpaid": "Unpaid",
  "common.overdue": "Overdue",
  "common.cancelled": "Cancelled",
  "common.active": "Active",
  "common.inactive": "Inactive",
  "common.language": "Language",
  "common.english": "English",
  "common.thai": "Thai",

  // Dashboard
  "dashboard.title": "Dashboard",
  "dashboard.dataFilters": "Data Filters",
  "dashboard.filterDesc": "Filter your tuition data by academic year, term, or date range",
  "dashboard.allData": "All data",
  "dashboard.filtered": "Filtered: ",
  "dashboard.filterOptions": "Filter Options",
  "dashboard.pickDateRange": "Pick a date range",
  "dashboard.quickActions": "Quick Actions",
  "dashboard.last30Days": "Last 30 Days",
  "dashboard.thisYear": "This Year",
  "dashboard.currentAcademicYear": "Current Academic Year",
  "dashboard.termOnly": "{term} Only",
  "dashboard.applyFilters": "Apply Filters",
  "dashboard.activeFilters": "Active Filters",
  "dashboard.studentsPaid": "Students Paid",
  "dashboard.totalRevenue": "Total Revenue",
  "dashboard.yearlyPayments": "Yearly Payments",
  "dashboard.termlyPayments": "Termly Payments",
  "dashboard.paymentTypeDistribution": "Payment Type Distribution",
  "dashboard.paymentChannels": "Payment Channels",
  "dashboard.revenueByTerm": "Revenue by Term",
  "dashboard.recentActivity": "Recent Payment Activity",
  "dashboard.yearly": "Yearly",
  "dashboard.termly": "Termly",

  // Invoice Management
  "invoice.title": "Invoice Management",
  "invoice.subtitle": "Create and manage student invoices with templates and discounts",
  "invoice.refreshed": "Invoice list refreshed",
  "invoice.importExcel": "Import Excel",
  "invoice.exportReport": "Export Report",
  "invoice.createInvoice": "Create Invoice",
  "invoice.invoiceList": "Invoice List",
  "invoice.invoiceNumber": "Invoice No.",
  "invoice.studentName": "Student Name",
  "invoice.studentId": "Student ID",
  "invoice.grade": "Grade",
  "invoice.room": "Room",
  "invoice.term": "Term",
  "invoice.academicYear": "Academic Year",
  "invoice.issueDate": "Issue Date",
  "invoice.dueDate": "Due Date",
  "invoice.subtotal": "Subtotal",
  "invoice.discount": "Discount",
  "invoice.netAmount": "Net Amount",
  "invoice.finalAmount": "Final Amount",
  "invoice.paymentStatus": "Payment Status",
  "invoice.pendingApproval": "Pending Approval",
  "invoice.viewInvoice": "View Invoice",
  "invoice.editInvoice": "Edit Invoice",
  "invoice.deleteInvoice": "Delete Invoice",
  "invoice.sendEmail": "Send Email",
  "invoice.markAsPaid": "Mark as Paid",
  "invoice.printInvoice": "Print Invoice",
  "invoice.downloadPdf": "Download PDF",
  "invoice.invoiceDetails": "Invoice Details",
  "invoice.items": "Items",
  "invoice.quantity": "Quantity",
  "invoice.unitPrice": "Unit Price",
  "invoice.discountPercent": "Discount %",
  "invoice.discountAmount": "Discount Amount",
  "invoice.totalAmount": "Total Amount",
  "invoice.paymentMethods": "Payment Methods",
  "invoice.bankTransfer": "Bank Transfer",
  "invoice.creditCard": "Credit Card",
  "invoice.cash": "Cash",
  "invoice.cheque": "Cheque",
  "invoice.billPayment": "Bill Payment",
  "invoice.latePaymentFee": "Late Payment Fee",
  "invoice.idCharges": "ID Charges",
  "invoice.registrationFee": "Registration Fee",
  "invoice.applicationFee": "Application Fee",
  "invoice.securityDeposit": "Security Deposit",
  "invoice.refundable": "Refundable",
  "invoice.feeWaiver": "Fee Waiver",
  "invoice.siblingDiscount": "Sibling Discount",
  "invoice.staffChildDiscount": "Staff Child Discount",
  "invoice.scholarship": "Scholarship",
  "invoice.earlyBirdDiscount": "Early Bird Discount",
  "invoice.newStudent": "New Student",
  "invoice.existingStudent": "Existing Student",
  "invoice.selectStudent": "Select Student",
  "invoice.selectItems": "Select Items",
  "invoice.selectTemplate": "Select Template",
  "invoice.paymentDeadline": "Payment Deadline",
  "invoice.preview": "Preview",
  "invoice.saveAsDraft": "Save as Draft",
  "invoice.createAndSend": "Create & Send",
  "invoice.approvalRequired": "Approval Required",
  "invoice.approvedBy": "Approved By",
  "invoice.rejectedReason": "Rejection Reason",
  "invoice.invoiceNotes": "Invoice Notes",
  "invoice.latePaymentPolicy": "Late payment charges of 1.5% per month or part thereof will be applied to payments made after the invoice due date.",
  "invoice.refundCondition": "The condition for refund of the security deposit is subject to the terms and conditions of King's College International School Bangkok.",
  "invoice.studentInvoices": "Student Invoices",
  "invoice.externalInvoices": "External Invoices",
  "invoice.recipientName": "Recipient Name",
  "invoice.recipientEmail": "Recipient Email",
  "invoice.recipientAddress": "Recipient Address",
  "invoice.eventName": "Event Name",
  "invoice.external": "External",
  "invoice.bulkActions": "Bulk Actions",
  "invoice.selectedInvoices": "Selected Invoices",
  "invoice.approveSelected": "Approve Selected",
  "invoice.rejectSelected": "Reject Selected",
  "invoice.sendSelected": "Send Selected",
  "invoice.exportSelected": "Export Selected",
  "invoice.statistics": "Statistics",
  "invoice.totalInvoices": "Total Invoices",
  "invoice.totalPending": "Total Pending",
  "invoice.totalApproved": "Total Approved",
  "invoice.totalRejected": "Total Rejected",
  "invoice.totalSent": "Total Sent",
  "invoice.totalPaid": "Total Paid",
  "invoice.totalOverdue": "Total Overdue",
  "invoice.totalRevenue": "Total Revenue",
  "invoice.filterByStatus": "Filter by Status",
  "invoice.filterByGrade": "Filter by Grade",
  "invoice.filterByTerm": "Filter by Term",
  "invoice.filterByDate": "Filter by Date",
  "invoice.searchPlaceholder": "Search by name, ID, or invoice number...",
  "invoice.noInvoicesFound": "No invoices found",
  "invoice.createFirstInvoice": "Create your first invoice",
  "invoice.confirmApproval": "Confirm Approval",
  "invoice.confirmApprovalMessage": "Are you sure you want to approve this invoice?",
  "invoice.confirmRejection": "Confirm Rejection",
  "invoice.confirmRejectionMessage": "Please provide a reason for rejecting this invoice.",
  "invoice.rejectionReasonPlaceholder": "Enter the reason for rejection...",
  "invoice.invoiceApproved": "Invoice approved successfully",
  "invoice.invoiceRejected": "Invoice rejected",
  "invoice.invoiceSent": "Invoice sent successfully",
  "invoice.invoiceDeleted": "Invoice deleted",
  "invoice.invoiceCreated": "Invoice created successfully",

  // After School
  "afterschool.title": "After School Dashboard",
  "afterschool.totalRegistrations": "Total Registrations",
  "afterschool.activeActivities": "Active Activities",
  "afterschool.averageAttendance": "Average Attendance",
  "afterschool.registrationTrend": "Registration & Revenue Trends",
  "afterschool.activityPopularity": "Activity Popularity",
  "afterschool.weeklyAttendance": "Weekly Attendance Pattern",
  "afterschool.revenueByActivity": "Revenue by Activity",
  "afterschool.capacityOverview": "Capacity Overview",
  "afterschool.recentRegistrations": "Recent Registrations",
  "afterschool.performanceAlerts": "Performance Alerts",
  "afterschool.highDemand": "High Demand Activities",
  "afterschool.lowRegistration": "Low Registration",
  "afterschool.topPerformers": "Top Performers",
  "afterschool.utilization": "Utilization",
  "afterschool.enrolled": "Enrolled",
  "afterschool.capacity": "Capacity",

  // Activities
  "activity.swimming": "Swimming",
  "activity.football": "Football",
  "activity.artCraft": "Art & Craft",
  "activity.music": "Music",
  "activity.basketball": "Basketball",
  "activity.drama": "Drama",
  "activity.chess": "Chess",
  "activity.coding": "Coding",
  "activity.swimmingPool": "Swimming Pool",
  "activity.footballField": "Football Field",
  "activity.artStudio": "Art Studio",
  "activity.musicRoom": "Music Room",
  "activity.basketballCourt": "Basketball Court",
  "invoice.invoiceSaved": "Invoice saved as draft",
  "invoice.fillRequiredFields": "Please fill in required fields",
  "invoice.selectAtLeastOneItem": "Please select at least one item",
  "invoice.selectAtLeastOneStudent": "Please select at least one student",
  "invoice.searchFilter": "Search & Filter",
  "invoice.apply": "Apply",
  "invoice.allYears": "All Years",
  "invoice.allTerms": "All Terms",
  "invoice.yearGroup": "Year Group",
  "invoice.allYearGroups": "All Year Groups",
  "invoice.allStatus": "All Status",
  "invoice.dateRange": "Date Range",
  "invoice.fromDate": "From Date",
  "invoice.toDate": "To Date",
  "invoice.selectDate": "Select date",
  "invoice.showingOf": "Showing {count} of {total} invoices",
  "invoice.showingRange": "Showing {from} to {to} of {total} invoices",
  "invoice.show": "Show",
  "invoice.entries": "entries",
  "invoice.previous": "Previous",
  "invoice.next": "Next",
  "invoice.student": "Student",
  "invoice.recipient": "Recipient",
  "invoice.event": "Event",
  "invoice.noExternalInvoices": "No external invoices",
  "invoice.createExternalDesc": "Create an external invoice to get started",
  "invoice.recipientInfo": "Recipient Information",
  "invoice.studentInfo": "Student Information",
  "invoice.contactName": "Contact Name",
  "invoice.invoiceInfo": "Invoice Details",
  "invoice.invoiceDate": "Invoice Date",
  "invoice.schoolYear": "School Year",
  "invoice.viewOnly": "View Only",
  "invoice.description": "Description",
  "invoice.newStudentFee": "New Student Fee",
  "invoice.siblingDiscountChild": "Sibling Discount (Child #{order})",
  "invoice.registrationFeeWaiverTerm": "Registration Fee Waiver (฿{amount}/term)",
  "invoice.securityDepositFeeWaiver": "Security Deposit Fee Waiver",
  "invoice.idChargesPercent": "ID Charges (3%)",
  "invoice.latePaymentFeePercent": "Late Payment Fee ({percent}%)",
  "invoice.paymentMethodsLabel": "Payment methods:",
  "invoice.paymentMethodsList": "Credit Card, PromptPay, Bank Counter, WeChat Pay, Alipay, Cash",
  "invoice.createNewInvoice": "Create New Invoice",
  "invoice.createInvoiceDesc": "Create an invoice using templates or custom items for students",
  "invoice.selectGrade": "Select Grade",
  "invoice.chooseGradeLevel": "Choose grade level",
  "invoice.availableItems": "Available Items for {grade}",
  "invoice.grades": "grades",
  "invoice.selectedItemsCount": "Selected Items ({count})",
  "invoice.clearAll": "Clear All",
  "invoice.item": "Item",
  "invoice.category": "Category",
  "invoice.totalItems": "Total Items",
  "invoice.students": "Students",
  "invoice.amountPerStudent": "Amount per Student",
  "invoice.noItemsForGrade": "No items available for this grade",
  "invoice.contactAdminForItems": "Please select a different grade or contact admin to add items",
  "invoice.selectStudents": "Select Students",
  "invoice.individual": "Individual",
  "invoice.selectSpecificStudents": "Select specific students",
  "invoice.csvUpload": "CSV Upload",
  "invoice.uploadStudentList": "Upload student list",
  "invoice.allStudents": "All Students",
  "invoice.selectEntireGrade": "Select entire grade",
  "invoice.searchByIdOrName": "Search by Student ID or name",
  "invoice.noStudentsFoundSearch": "No students found",
  "invoice.uploadCsvDesc": "Upload CSV file with student information",
  "invoice.fileUploaded": "File uploaded:",
  "invoice.loadedStudents": "Loaded {count} students",
  "invoice.selectAllIn": "Select all students in {grade}",
  "invoice.studentsWillBeSelected": "{count} students will be selected",
  "invoice.selectAllStudentsBtn": "Select All Students",
  "invoice.selectedStudentsCount": "Selected Students ({count})",
  "invoice.createInvoiceStep": "Create Invoice",
  "invoice.invoiceSummary": "Invoice Summary",

  // Invoice Creation
  "invoiceCreate.title": "Create Invoice",
  "invoiceCreate.step1": "Select Academic Year & Term",
  "invoiceCreate.step2": "Select Grade & Room",
  "invoiceCreate.step3": "Select Students",
  "invoiceCreate.step4": "Select Items",
  "invoiceCreate.step5": "Set Payment Deadline",
  "invoiceCreate.step6": "Preview & Confirm",
  "invoiceCreate.academicYear": "Academic Year",
  "invoiceCreate.selectAcademicYear": "Select Academic Year",
  "invoiceCreate.term": "Term",
  "invoiceCreate.selectTerm": "Select Term",
  "invoiceCreate.grade": "Grade",
  "invoiceCreate.selectGrade": "Select Grade",
  "invoiceCreate.room": "Room",
  "invoiceCreate.selectRoom": "Select Room",
  "invoiceCreate.allRooms": "All Rooms",
  "invoiceCreate.students": "Students",
  "invoiceCreate.selectedStudents": "Selected Students",
  "invoiceCreate.noStudentsSelected": "No students selected",
  "invoiceCreate.selectAllStudents": "Select All Students",
  "invoiceCreate.clearSelection": "Clear Selection",
  "invoiceCreate.addNewStudent": "Add New Student",
  "invoiceCreate.importFromCsv": "Import from CSV",
  "invoiceCreate.items": "Items",
  "invoiceCreate.selectedItems": "Selected Items",
  "invoiceCreate.noItemsSelected": "No items selected",
  "invoiceCreate.addItem": "Add Item",
  "invoiceCreate.removeItem": "Remove Item",
  "invoiceCreate.itemName": "Item Name",
  "invoiceCreate.itemDescription": "Item Description",
  "invoiceCreate.itemAmount": "Item Amount",
  "invoiceCreate.template": "Template",
  "invoiceCreate.selectTemplate": "Select Template",
  "invoiceCreate.noTemplate": "No Template",
  "invoiceCreate.paymentDeadline": "Payment Deadline",
  "invoiceCreate.selectDate": "Select Date",
  "invoiceCreate.preview": "Preview Invoice",
  "invoiceCreate.previewDescription": "Review the invoice details before creating",
  "invoiceCreate.billTo": "Bill To",
  "invoiceCreate.invoiceInfo": "Invoice Information",
  "invoiceCreate.itemsAndFees": "Items & Fees",
  "invoiceCreate.discounts": "Discounts",
  "invoiceCreate.summary": "Summary",
  "invoiceCreate.submitForApproval": "Submit for Approval",
  "invoiceCreate.createAndSendEmail": "Create & Send Email",
  "invoiceCreate.backToEdit": "Back to Edit",
  "invoiceCreate.confirmCreate": "Confirm Create",
  "invoiceCreate.invoicePreview": "Invoice Preview",
  "invoiceCreate.studentInfo": "Student Information",
  "invoiceCreate.parentInfo": "Parent Information",
  "invoiceCreate.parentName": "Parent Name",
  "invoiceCreate.parentEmail": "Parent Email",
  "invoiceCreate.parentPhone": "Parent Phone",
  "invoiceCreate.registrationFees": "Registration Fees",
  "invoiceCreate.registrationFeesNote": "The following fees will be automatically applied to new students:",
  "invoiceCreate.idChargesNote": "ID Charges (3%) will be automatically calculated",
  "invoiceCreate.latePaymentNote": "Late payment charges will apply after due date",
  "invoiceCreate.externalInvoice": "External Invoice",
  "invoiceCreate.externalInvoiceDescription": "Create invoice for external recipients (non-students)",
  "invoiceCreate.recipientDetails": "Recipient Details",
  "invoiceCreate.firstName": "First Name",
  "invoiceCreate.lastName": "Last Name",
  "invoiceCreate.nickname": "Nickname",
  "invoiceCreate.gender": "Gender",
  "invoiceCreate.male": "Male",
  "invoiceCreate.female": "Female",
  "invoiceCreate.dateOfBirth": "Date of Birth",
  "invoiceCreate.familyType": "Family Type",
  "invoiceCreate.createNewFamily": "Create New Family",
  "invoiceCreate.joinExistingFamily": "Join Existing Family (Sibling)",
  "invoiceCreate.selectFamily": "Select Family",
  "invoiceCreate.childOrder": "Child Order",
  "invoiceCreate.parentGuardianInfo": "Parent/Guardian Information",
  "invoiceCreate.parentGuardianName": "Parent/Guardian Name",
  "invoiceCreate.relationship": "Relationship",
  "invoiceCreate.father": "Father",
  "invoiceCreate.mother": "Mother",
  "invoiceCreate.guardian": "Guardian",
  "invoiceCreate.other": "Other",
  "invoiceCreate.amountInWords": "Amount in Words",

  // Student List
  "student.title": "Student List",
  "student.description": "Manage student information and enrollment",
  "student.addStudent": "Add Student",
  "student.editStudent": "Edit Student",
  "student.deleteStudent": "Delete Student",
  "student.viewStudent": "View Student",
  "student.promoteGrade": "Promote Grade",
  "student.families": "Family",
  "student.studentDetails": "Student Details",
  "student.personalInfo": "Personal Information",
  "student.academicInfo": "Academic Information",
  "student.familyInfo": "Family Information",
  "student.contactInfo": "Contact Information",
  "student.firstName": "First Name",
  "student.lastName": "Last Name",
  "student.nickname": "Nickname",
  "student.gender": "Gender",
  "student.dateOfBirth": "Date of Birth",
  "student.studentId": "Student ID",
  "student.grade": "Grade",
  "student.room": "Room",
  "student.academicYear": "Academic Year",
  "student.enrollmentDate": "Enrollment Date",
  "student.enrollmentTerm": "Enrollment Term",
  "student.status": "Status",
  "student.familyId": "Family ID",
  "student.childOrder": "Child Order",
  "student.parents": "Parents",
  "student.parentName": "Parent Name",
  "student.parentEmail": "Parent Email",
  "student.parentPhone": "Parent Phone",
  "student.relationship": "Relationship",
  "student.notes": "Notes",
  "student.createdAt": "Created At",
  "student.updatedAt": "Updated At",
  "student.searchPlaceholder": "Search students...",
  "student.filterByGrade": "Filter by Grade",
  "student.filterByStatus": "Filter by Status",
  "student.noStudentsFound": "No students found",
  "student.totalStudents": "Total Students",
  "student.activeStudents": "Active Students",
  "student.inactiveStudents": "Inactive Students",
  "student.newStudents": "New Students",
  "student.importStudents": "Import Students",
  "student.exportStudents": "Export Students",
  "student.confirmDelete": "Are you sure you want to delete this student?",
  "student.deleteWarning": "This action cannot be undone.",
  "student.studentAdded": "Student added successfully",
  "student.studentUpdated": "Student updated successfully",
  "student.studentDeleted": "Student deleted successfully",

  // Item Management
  "item.title": "Items / Templates",
  "item.items": "Items",
  "item.templates": "Templates",
  "item.chooseInvoiceType": "Choose the type of invoice you want to create",
  "item.applicationRegFees": "Application & Registration Fees",
  "item.configureInitialCharges": "Configure initial charges for new applicants",
  "item.feeType": "Fee Type",
  "item.amountTHB": "Amount (THB)",
  "item.refundable": "Refundable",
  "item.addItem": "Add Item",
  "item.editItem": "Edit Item",
  "item.deleteItem": "Delete Item",
  "item.itemName": "Item Name",
  "item.itemCode": "Item Code",
  "item.category": "Category",
  "item.amount": "Amount",
  "item.description": "Description",
  "item.isActive": "Active",
  "item.addTemplate": "Add Template",
  "item.editTemplate": "Edit Template",
  "item.deleteTemplate": "Delete Template",
  "item.templateName": "Template Name",
  "item.templateItems": "Template Items",
  "item.totalAmount": "Total Amount",
  "item.itemsCount": "Items Count",
  "item.noItemsFound": "No items found",
  "item.noTemplatesFound": "No templates found",
  "item.searchItems": "Search items...",
  "item.searchTemplates": "Search templates...",
  "item.filterByCategory": "Filter by Category",
  "item.tuition": "Tuition",
  "item.activities": "Activities",
  "item.transportation": "Transportation",
  "item.meals": "Meals",
  "item.uniform": "Uniform",
  "item.books": "Books",
  "item.events": "Events",
  "item.others": "Others",
  "item.itemAdded": "Item added successfully",
  "item.itemUpdated": "Item updated successfully",
  "item.itemDeleted": "Item deleted successfully",
  "item.templateAdded": "Template added successfully",
  "item.templateUpdated": "Template updated successfully",
  "item.templateDeleted": "Template deleted successfully",
  "item.confirmDeleteItem": "Are you sure you want to delete this item?",
  "item.confirmDeleteTemplate": "Are you sure you want to delete this template?",

  // Discount Management
  "discount.title": "Discount Management",
  "discount.subtitle": "Manage discount codes and analyze discount performance",
  "discount.overview": "Overview",
  "discount.studentGroups": "Student Groups",
  "discount.promotions": "Promotions",
  "discount.waiveFees": "Waive Fees",
  "discount.reports": "Reports",
  "discount.addDiscount": "Add Discount",
  "discount.editDiscount": "Edit Discount",
  "discount.deleteDiscount": "Delete Discount",
  "discount.discountName": "Discount Name",
  "discount.discountType": "Discount Type",
  "discount.percentage": "Percentage",
  "discount.fixedAmount": "Fixed Amount",
  "discount.discountValue": "Discount Value",
  "discount.applicableTo": "Applicable To",
  "discount.startDate": "Start Date",
  "discount.endDate": "End Date",
  "discount.isActive": "Active",
  "discount.conditions": "Conditions",
  "discount.siblingDiscount": "Sibling Discount",
  "discount.staffChildDiscount": "Staff Child Discount",
  "discount.scholarshipDiscount": "Scholarship",
  "discount.earlyBirdDiscount": "Early Bird Discount",
  "discount.feeWaiver": "Fee Waiver",
  "discount.feeWaiverProgram": "Fee Waiver Program",
  "discount.feeWaiverDescription": "Fee waiver for students who have completed 3+ years (2nd child or later)",
  "discount.registrationFeeWaiver": "Registration Fee Waiver",
  "discount.securityDepositWaiver": "Security Deposit Fee Waiver",
  "discount.eligibility": "Eligibility",
  "discount.creditPerTerm": "Credit Per Term",
  "discount.termsRemaining": "Terms Remaining",
  "discount.totalCredit": "Total Credit",
  "discount.noDiscountsFound": "No discounts found",
  "discount.discountAdded": "Discount added successfully",
  "discount.discountUpdated": "Discount updated successfully",
  "discount.discountDeleted": "Discount deleted successfully",

  // Discount Options
  "discountOptions.title": "Discount Options",
  "discountOptions.subtitle": "Configure sibling discounts, late payment charges, and registration fee privileges",
  "discountOptions.saveAllChanges": "Save All Changes",
  "discountOptions.siblingDiscounts": "Sibling Discounts",
  "discountOptions.siblingDiscountsDesc": "Siblings in the School at the same time are eligible for a discount on tuition fees. In cases that the eldest sibling graduates at the end of Year 13, the younger siblings will maintain their sibling rights.",
  "discountOptions.enabled": "Enabled",
  "discountOptions.childOrder": "Child Order",
  "discountOptions.discountPercentage": "Discount Percentage",
  "discountOptions.preview": "Preview",
  "discountOptions.off": "off",
  "discountOptions.noDiscount": "No discount",
  "discountOptions.confirmSaveChanges": "Confirm Save Changes",
  "discountOptions.confirmSaveDesc": "Are you sure you want to save all discount options for academic year {year}?",
  "discountOptions.configured": "configured",
  "discountOptions.latePayment": "Late Payment",
  "discountOptions.disabled": "Disabled",
  "discountOptions.perMonth": "per month",
  "discountOptions.perWeek": "per week",
  "discountOptions.totalInitialFees": "Total Initial Fees",
  "discountOptions.confirmSave": "Confirm Save",
  "discountOptions.savedSuccess": "Discount options saved for {year}",
  "discountOptions.feesAndTuition": "Fees and Tuition Information - Academic Year {year}",
  "discountOptions.firstChild": "First Child",
  "discountOptions.secondChild": "Second Child",
  "discountOptions.thirdChild": "Third Child",
  "discountOptions.fourthChild": "Fourth Child",
  "discountOptions.fifthChild": "Fifth Child and subsequent",
  "discountOptions.academicYear": "Academic Year",
  "discountOptions.selectYear": "Select year",
  "discountOptions.schoolName": "King's College International School Bangkok",
  "discountOptions.feesInfo": "Fees and Tuition Information - Academic Year {year}",
  "discountOptions.confirmSaveTitle": "Confirm Save Changes",
  "discountOptions.confirmSaveMessage": "Are you sure you want to save all discount options for academic year {year}?",
  "discountOptions.per": "per",
  "discountOptions.month": "month",
  "discountOptions.week": "week",
  "discountOptions.percentOff": "{percent}% off",
  "discountOptions.cancel": "Cancel",

  // Discount Reports
  "discountReports.title": "Discount Reports",
  "discountReports.subtitle": "View student discount details and generate reports",
  "discountReports.exportCsv": "Export CSV",
  "discountReports.totalStudents": "Total Students",
  "discountReports.withDiscountsApplied": "with discounts applied",
  "discountReports.totalDiscount": "Total Discount",
  "discountReports.totalSavingsProvided": "total savings provided",
  "discountReports.averageDiscount": "Average Discount",
  "discountReports.avgPercentageDiscount": "avg percentage discount",
  "discountReports.yearGroups": "Year Groups",
  "discountReports.withDiscountStudents": "with discount students",
  "discountReports.searchFilter": "Search & Filter",
  "discountReports.apply": "Apply",
  "discountReports.clear": "Clear",
  "discountReports.search": "Search",
  "discountReports.nameOrId": "Name or ID...",
  "discountReports.yearGroup": "Year Group",
  "discountReports.allYearGroups": "All Year Groups",
  "discountReports.discountType": "Discount Type",
  "discountReports.allTypes": "All Types",
  "discountReports.sibling": "Sibling",
  "discountReports.scholarship": "Scholarship",
  "discountReports.staff": "Staff",
  "discountReports.earlyBird": "Early Bird",
  "discountReports.group": "Group",
  "discountReports.campaign": "Campaign",
  "discountReports.feeWaiver": "Fee Waiver",
  "discountReports.status": "Status",
  "discountReports.allStatus": "All Status",
  "discountReports.active": "Active",
  "discountReports.pending": "Pending",
  "discountReports.expired": "Expired",
  "discountReports.studentDiscountDetails": "Student Discount Details",
  "discountReports.showingOf": "Showing {shown} of {total} students",
  "discountReports.studentId": "Student ID",
  "discountReports.studentName": "Student Name",
  "discountReports.parent": "Parent",
  "discountReports.discountTypes": "Discount Types",
  "discountReports.discountsDetail": "Discounts Detail",
  "discountReports.amount": "Amount",
  "discountReports.discount": "Discount",
  "discountReports.net": "Net",
  "discountReports.appliedTo": "Applied To",
  "discountReports.noStudentsFound": "No students found matching the filters",
  "discountReports.discountByType": "Discount by Type",
  "discountReports.breakdownByCategory": "Breakdown of discounts by category",
  "discountReports.students": "students",
  "discountReports.discountByYearGroup": "Discount by Year Group",
  "discountReports.breakdownByYearGroup": "Breakdown of discounts by year group",

  // Waive Fee Management
  "waiveFee.title": "Waive Fee Management Dashboard",
  "waiveFee.subtitle": "Track and manage sibling discount waivers across academic years",
  "waiveFee.exportData": "Export Data",
  "waiveFee.importCsv": "Import CSV",
  "waiveFee.academicYear": "Academic Year",
  "waiveFee.reset": "Reset",
  "waiveFee.totalStudents": "Total Students",
  "waiveFee.receivingWaivers": "receiving waivers in {year}",
  "waiveFee.totalFamilies": "Total Family",
  "waiveFee.familiesBenefiting": "family benefiting from waiver",
  "waiveFee.totalWaiverAmount": "Total Waiver Amount",
  "waiveFee.totalWaiversFor": "total waivers for {year}",
  "waiveFee.averagePerFamily": "Average per Family",
  "waiveFee.avgWaiverPerFamily": "average waiver per family",
  "waiveFee.registrationFeeWaiverProgram": "Registration Fee Waiver Program",
  "waiveFee.configureWaiver": "Configure waiver eligibility and credit distribution",
  "waiveFee.minYearGroup": "Min Year Group",
  "waiveFee.minTerms1stChild": "Min Terms (1st child)",
  "waiveFee.creditAmountThb": "Credit Amount (THB)",
  "waiveFee.termsToCredit": "Terms to Credit",
  "waiveFee.firstChildPrivilege": "First Child Gets Privilege Immediately",
  "waiveFee.skipMinTerms": "Skip minimum terms requirement for first child",
  "waiveFee.eligibilitySummary": "Eligibility Summary",
  "waiveFee.yearPlusStudents": "Year {year}+ students",
  "waiveFee.firstChildImmediate": "1st child: Immediate",
  "waiveFee.firstChildAfterTerms": "1st child: After {terms} terms",
  "waiveFee.secondChildImmediate": "2nd child+: Immediate from Year {year}",
  "waiveFee.creditPerTerm": "Credit: {amount}/term x {terms} terms",
  "waiveFee.multiYearSummary": "Multi-Year Waiver Summary Matrix",
  "waiveFee.avgWaiverAcrossYears": "Average waiver amount per student across all academic years and terms",
  "waiveFee.term": "Term {num}",
  "waiveFee.viewMore": "View More",
  "waiveFee.studentsCount": "{count} students",
  "waiveFee.familiesCount": "{count} family",
  "waiveFee.olderSibling": "พี่",
  "waiveFee.youngerSibling": "น้อง",
  "waiveFee.yearTotal": "Year Total",
  "waiveFee.total": "total",
  "waiveFee.noteValues": "Values show average waiver amount per student. Years 1-3: Younger siblings receive discounts. Years 4-6: Older siblings receive discounts. Each cell shows: Average Amount / Number of Students / Number of Family / Sibling Distribution",
  "waiveFee.active": "Active",
  "waiveFee.completed": "Completed",
  "waiveFee.pending": "Pending",

  // Family Groups
  "familyGroups.title": "Family Group",
  "familyGroups.subtitle": "Manage family groups and sibling relationships for discount calculation",
  "familyGroups.addFamily": "Add Family",
  "familyGroups.totalFamilies": "Total Family",
  "familyGroups.studentsInFamilies": "Students in Family",
  "familyGroups.multiChildFamilies": "Multi-Child Family",
  "familyGroups.studentsWithDiscount": "Students with Discount",
  "familyGroups.searchFamilies": "Search family...",
  "familyGroups.noFamiliesFound": "No family found. Create a family to group siblings together.",
  "familyGroups.family": "Family",
  "familyGroups.children": "children",
  "familyGroups.noAddressProvided": "No address provided",
  "familyGroups.totalDiscount": "Total: {percent}% discount",
  "familyGroups.noStudentsInFamily": "No students in this family yet. Add students to calculate sibling discounts.",
  "familyGroups.order": "Order",
  "familyGroups.student": "Student",
  "familyGroups.studentId": "Student ID",
  "familyGroups.yearGroup": "Year Group",
  "familyGroups.siblingDiscount": "Sibling Discount",
  "familyGroups.feeWaiver": "Fee Waiver",
  "familyGroups.actions": "Actions",
  "familyGroups.off": "% off",
  "familyGroups.noDiscount": "No discount",
  "familyGroups.remove": "Remove",
  "familyGroups.siblingDiscountSummary": "Sibling Discount Summary",
  "familyGroups.discountLabel": "{percent}% discount",
  "familyGroups.registrationFeeWaiverProgram": "Registration Fee Waiver Program",
  "familyGroups.perTerm": "/term",
  "familyGroups.pending": "Pending",
  "familyGroups.show": "Show",
  "familyGroups.entries": "entries",
  "familyGroups.showingOf": "Showing {from} to {to} of {total} family",
  "familyGroups.previous": "Previous",
  "familyGroups.next": "Next",
  "familyGroups.studentsNotAssigned": "Students Not Assigned to a Family",
  "familyGroups.notAssignedDesc": "These students are not part of any family group and won't receive sibling discounts",
  "familyGroups.more": "+{count} more",
  "familyGroups.createNewFamily": "Create New Family",
  "familyGroups.editFamily": "Edit Family",
  "familyGroups.deleteFamily": "Delete Family",
  "familyGroups.familyCode": "Family Code",
  "familyGroups.familyName": "Family Name",
  "familyGroups.address": "Address",
  "familyGroups.email": "Email",
  "familyGroups.emailForInvoices": "Email (for invoices)",
  "familyGroups.phone": "Phone",
  "familyGroups.cancel": "Cancel",
  "familyGroups.createFamily": "Create Family",
  "familyGroups.saveChanges": "Save Changes",
  "familyGroups.confirmDeleteFamily": "Are you sure you want to delete the {name} family?",
  "familyGroups.deleteWarning": "All students in this family will be removed from the family group and will lose their sibling discounts.",
  "familyGroups.addStudentTo": "Add Student to {name} Family",
  "familyGroups.allStudentsAssigned": "All students are already assigned to a family.",
  "familyGroups.selectStudent": "Select Student",
  "familyGroups.selectAStudent": "Select a student",
  "familyGroups.willBeAddedAsChild": "The student will be added as child #{num}",
  "familyGroups.addToFamily": "Add to Family",
  "familyGroups.familyCreated": "Family created successfully",
  "familyGroups.familyUpdated": "Family updated successfully",
  "familyGroups.familyDeleted": "Family deleted successfully",
  "familyGroups.studentAdded": "Student added to family",
  "familyGroups.studentRemoved": "Student removed from family",

  // Messages & Notifications
  "message.success": "Success",
  "message.error": "Error",
  "message.warning": "Warning",
  "message.info": "Information",
  "message.confirm": "Confirm",
  "message.areYouSure": "Are you sure?",
  "message.actionCannotBeUndone": "This action cannot be undone.",
  "message.savedSuccessfully": "Saved successfully",
  "message.deletedSuccessfully": "Deleted successfully",
  "message.updatedSuccessfully": "Updated successfully",
  "message.createdSuccessfully": "Created successfully",
  "message.sentSuccessfully": "Sent successfully",
  "message.operationFailed": "Operation failed",
  "message.pleaseWait": "Please wait...",
  "message.processingRequest": "Processing your request...",
  "message.noResultsFound": "No results found",
  "message.tryDifferentSearch": "Try a different search term",

  // Validation
  "validation.required": "This field is required",
  "validation.invalidEmail": "Invalid email address",
  "validation.invalidPhone": "Invalid phone number",
  "validation.minLength": "Minimum length is {min} characters",
  "validation.maxLength": "Maximum length is {max} characters",
  "validation.minValue": "Minimum value is {min}",
  "validation.maxValue": "Maximum value is {max}",
  "validation.invalidDate": "Invalid date",
  "validation.dateInPast": "Date must be in the past",
  "validation.dateInFuture": "Date must be in the future",
  "validation.passwordMismatch": "Passwords do not match",
  "validation.invalidFormat": "Invalid format",

  // Date & Time
  "date.today": "Today",
  "date.yesterday": "Yesterday",
  "date.tomorrow": "Tomorrow",
  "date.thisWeek": "This Week",
  "date.lastWeek": "Last Week",
  "date.thisMonth": "This Month",
  "date.lastMonth": "Last Month",
  "date.thisYear": "This Year",
  "date.lastYear": "Last Year",
  "date.custom": "Custom",
  "date.from": "From",
  "date.to": "To",

  // Roles & Permissions
  "roles.title": "Roles & Permissions",
  "roles.subtitle": "Manage user roles and access permissions",
  "roles.addRole": "Add Role",
  "roles.editRole": "Edit Role",
  "roles.deleteRole": "Delete Role",
  "roles.roleName": "Role Name",
  "roles.description": "Description",
  "roles.permissions": "Permissions",
  "roles.users": "Users",
  "roles.assignedUsers": "Assigned Users",
  "roles.roleDetails": "Role Details",
  "roles.permissionModules": "Permission Modules",
  "roles.selectAll": "Select All",
  "roles.noRolesFound": "No roles found",
  "roles.roleCreated": "Role created successfully",
  "roles.roleUpdated": "Role updated successfully",
  "roles.roleDeleted": "Role deleted successfully",
  "roles.cannotDeleteDefault": "Cannot delete system default roles",
  "roles.view": "View",
  "roles.create": "Create",
  "roles.edit": "Edit",
  "roles.delete": "Delete",
  "roles.manage": "Manage",
  "roles.export": "Export",
  "roles.void": "Void",
  "roles.sendEmail": "Send Email",
  "roles.download": "Download",
  "roles.createNewRole": "Create New Role",
  "roles.createNewRoleDesc": "Define a new role with specific permissions",
  "roles.editRoleInfo": "Edit role information and permissions",
  "roles.roleNamePlaceholder": "Enter role name",
  "roles.descriptionPlaceholder": "Enter role description",

  // User Management
  "users.title": "User Management",
  "users.subtitle": "Manage user accounts and access",
  "users.addUser": "Add User",
  "users.editUser": "Edit User",
  "users.deleteUser": "Delete User",
  "users.userName": "User Name",
  "users.email": "Email",
  "users.role": "Role",
  "users.status": "Status",
  "users.lastLogin": "Last Login",
  "users.active": "Active",
  "users.inactive": "Inactive",
  "users.suspended": "Suspended",
  "users.userCreated": "User created successfully",
  "users.userUpdated": "User updated successfully",
  "users.userDeleted": "User deleted successfully",
  "users.resetPassword": "Reset Password",
  "users.sendInvite": "Send Invite",
  "users.department": "Department",
  "users.position": "Position",
  "users.searchPlaceholder": "Search by name, email...",
  "users.allRoles": "All Roles",
  "users.allStatuses": "All Statuses",
  "users.createNewUser": "Create New User",
  "users.createNewUserDesc": "Add a new user to the system",
  "users.editUserInfo": "Edit user information and permissions",

  // Credit Note Management
  "creditNote.title": "Credit Note Management",
  "creditNote.subtitle": "Manage credit notes, refunds, and billing adjustments",
  "creditNote.createCreditNote": "Create Credit Note",
  "creditNote.totalCreditNotes": "Total Credit Notes",
  "creditNote.draft": "Draft",
  "creditNote.issued": "Issued",
  "creditNote.applied": "Applied",
  "creditNote.totalCreditAmount": "Total Credit Amount",
  "creditNote.creditNoteNumber": "Credit Note Number",
  "creditNote.invoiceReference": "Invoice Reference",
  "creditNote.searchPlaceholder": "Credit note, invoice, student...",
  "creditNote.allTypes": "All Types",
  "creditNote.refund": "Refund",
  "creditNote.adjustment": "Adjustment",
  "creditNote.cancellation": "Cancellation",
  "creditNote.discount": "Discount",
  "creditNote.showingOf": "Showing {count} of {total} credit notes",
  "creditNote.creditNoteDetails": "Credit Note Details",
  "creditNote.creditNoteDetailsDesc": "View and manage credit note information and processing details",
  "creditNote.studentInfo": "Student Information",
  "creditNote.studentName": "Student Name",
  "creditNote.parentGuardian": "Parent/Guardian",
  "creditNote.creditInfo": "Credit Information",
  "creditNote.relatedInvoice": "Related Invoice",
  "creditNote.originalAmount": "Original Amount",
  "creditNote.creditAmount": "Credit Amount",
  "creditNote.creditDetails": "Credit Details",
  "creditNote.reason": "Reason",
  "creditNote.appliedDate": "Applied Date",
  "creditNote.processingInfo": "Processing Information",
  "creditNote.issuedBy": "Issued By",
  "creditNote.approvedBy": "Approved By",
  "creditNote.notes": "Notes",
  "creditNote.sendToParent": "Send to Parent",
  "creditNote.createNewCreditNote": "Create New Credit Note",
  "creditNote.createNewDesc": "Create a new credit note for refunds, adjustments, or cancellations",
  "creditNote.selectInvoice": "Select Invoice",
  "creditNote.selectAnInvoice": "Select an invoice...",
  "creditNote.noInvoicesFound": "No invoices found. Create invoices first.",
  "creditNote.invoiceDetails": "Invoice Details",
  "creditNote.creditType": "Credit Type",
  "creditNote.billingAdjustment": "Billing Adjustment",
  "creditNote.courseCancellation": "Course Cancellation",
  "creditNote.discountApplied": "Discount Applied",
  "creditNote.enterReason": "Enter reason for credit note",
  "creditNote.additionalNotes": "Additional Notes",
  "creditNote.enterAdditionalNotes": "Enter any additional notes or comments",
  "creditNote.createdSuccess": "Credit note {number} created successfully",
  "creditNote.downloaded": "Credit note {number} downloaded",
  "creditNote.sentTo": "Credit note sent to {name}",
  "creditNote.selectInvoiceAndFill": "Please select an invoice and fill in all required fields",
  "creditNote.enterValidAmount": "Please enter a valid credit amount",
  "creditNote.cannotExceed": "Credit amount cannot exceed original invoice amount",
  "creditNote.showEntries": "Show",
  "creditNote.entries": "entries",

  // Invoice Email Management
  "invoiceEmail.title": "Invoice Email Management",
  "invoiceEmail.subtitle": "Send invoice emails to parents with automated templates and delivery tracking",
  "invoiceEmail.sendEmails": "Send Emails",
  "invoiceEmail.emailJobs": "Email Jobs",
  "invoiceEmail.sendingOptions": "Email Sending Options",
  "invoiceEmail.sendAll": "Send All",
  "invoiceEmail.sendAllDesc": "Send to all students in the system",
  "invoiceEmail.batchSend": "Batch Send",
  "invoiceEmail.batchSendDesc": "Send to filtered groups",
  "invoiceEmail.individualSend": "Individual Send",
  "invoiceEmail.individualSendDesc": "Send to specific students",
  "invoiceEmail.students": "students",
  "invoiceEmail.selected": "selected",
  "invoiceEmail.filterCriteria": "Filter Criteria",
  "invoiceEmail.grades": "Grades",
  "invoiceEmail.studentStatus": "Student Status",
  "invoiceEmail.applyFilters": "Apply Filters",
  "invoiceEmail.selectStudents": "Select Students",
  "invoiceEmail.searchPlaceholder": "Search by name, student ID, family code...",
  "invoiceEmail.selectedStudents": "Selected Students",
  "invoiceEmail.emailTemplate": "Email Template",
  "invoiceEmail.previewEmail": "Preview Email",
  "invoiceEmail.sendControls": "Send Controls",
  "invoiceEmail.recipients": "Recipients",
  "invoiceEmail.template": "Template",
  "invoiceEmail.estimatedTime": "Estimated Time",
  "invoiceEmail.minutes": "minutes",
  "invoiceEmail.sendingEmails": "Sending emails...",
  "invoiceEmail.sendEmails2": "Send {count} Emails",
  "invoiceEmail.sendingEmailsBtn": "Sending Emails...",
  "invoiceEmail.emailHistory": "Email Sending History",
  "invoiceEmail.jobName": "Job Name",
  "invoiceEmail.progress": "Progress",
  "invoiceEmail.created": "Created",
  "invoiceEmail.createdBy": "Created By",
  "invoiceEmail.emailPreview": "Email Preview",
  "invoiceEmail.previewDesc": "Preview how the email will look for parents",
  "invoiceEmail.selectStudent": "Select student",
  "invoiceEmail.to": "To",
  "invoiceEmail.subject": "Subject",
  "invoiceEmail.message": "Message",
  "invoiceEmail.footer": "Footer",
  "invoiceEmail.attachment": "Attachment",
  "invoiceEmail.noStudentsPreview": "No students available for preview",
  "invoiceEmail.selectRecipients": "Please select recipients before sending",
  "invoiceEmail.emailsSent": "Emails sent successfully! {sent} sent, {failed} failed",
  "invoiceEmail.sent": "Sent",
  "invoiceEmail.failed": "failed",
  "invoiceEmail.pending": "Pending",
  "invoiceEmail.running": "Running",
  "invoiceEmail.completed": "Completed",
  "invoiceEmail.cancelled": "Cancelled",
  "invoiceEmail.default": "Default",

  // Invoice Overview
  "invoiceOverview.title": "Invoice Overview",
  "invoiceOverview.subtitle": "Manage all invoices and track payment status",
  "invoiceOverview.totalInvoices": "Total Invoices",
  "invoiceOverview.paidInvoices": "Paid Invoices",
  "invoiceOverview.unpaidInvoices": "Unpaid Invoices",
  "invoiceOverview.overdueInvoices": "Overdue Invoices",
  "invoiceOverview.totalValue": "Total value",
  "invoiceOverview.ofTotal": "of total",
  "invoiceOverview.searchFilter": "Search & Filter",
  "invoiceOverview.searchPlaceholder": "Invoice, student, parent...",
  "invoiceOverview.noInvoicesYet": "No invoices yet",
  "invoiceOverview.noInvoicesDescription": "Invoices created from the \"Create Invoice\" page will appear here. Go to Invoice Management → Create Invoice to create new invoices.",
  "invoiceOverview.showing": "Showing",
  "invoiceOverview.of": "of",
  "invoiceOverview.invoices": "invoices",
  "invoiceOverview.filteredFrom": "filtered from",
  "invoiceOverview.total": "total",
  "invoiceOverview.page": "Page",
  "invoiceOverview.goToPage": "Go to page",
  "invoiceOverview.daysOverdue": "days overdue",
  "invoiceOverview.daysLeft": "days left",
  "invoiceOverview.daysRemaining": "days remaining",
  "invoiceOverview.sent": "sent",
  "invoiceOverview.viewDetails": "View Details",
  "invoiceOverview.downloadInvoice": "Download Invoice",
  "invoiceOverview.sendReminder": "Send Reminder",
  "invoiceOverview.invoiceDetails": "Invoice Details",
  "invoiceOverview.viewInvoiceInfo": "View complete invoice information, payment status, and send reminders",
  "invoiceOverview.studentInfo": "Student Information",
  "invoiceOverview.fullName": "Full Name",
  "invoiceOverview.financialDetails": "Financial Details",
  "invoiceOverview.amountDue": "Amount Due",
  "invoiceOverview.academicTerm": "Academic Term",
  "invoiceOverview.importantDates": "Important Dates",
  "invoiceOverview.communicationHistory": "Communication History",
  "invoiceOverview.paymentRemindersSent": "Payment Reminders Sent",
  "invoiceOverview.totalRemindersDescription": "Total reminders sent to parent/guardian",
  "invoiceOverview.reminderSent": "Reminder sent to {name}'s parent",
  "invoiceOverview.invoiceDownloaded": "Invoice {number} downloaded",
  "invoiceOverview.listRefreshed": "Invoice list refreshed",
  "invoiceOverview.downloadSuccess": "Invoice downloaded successfully",
  "invoiceOverview.yearly": "Yearly",
  "invoiceOverview.termly": "Termly",
  "invoiceOverview.channel": "Channel",
  "invoiceOverview.reminders": "Reminders",
  "invoiceOverview.type": "Type",

  // School Info
  "school.name": "King's College International School Bangkok",
  "school.address": "99/1 Moo 5, Soi Serithai 35, Khannayao, Bangkok 10230",
  "school.phone": "+66 2 138 5455",
  "school.email": "admissions@kingsbangkok.ac.th",
  "school.website": "www.kingsbangkok.ac.th",
  "school.taxId": "0105559012345",
}

// Thai translations
const th: Record<string, string> = {
  // App - Sidebar Menu
  "menu.tuitionManagement": "ค่าเทอม",
  "menu.dashboard": "ภาพรวม",
  "menu.termSettings": "ตั้งค่าเทอม",
  "menu.debtReminder": "แจ้งเตือนค้างชำระ",
  "menu.paymentHistory": "ประวัติการชำระ",
  "menu.transactions": "รายการทั้งหมด",
  "menu.afterSchool": "กิจกรรมหลังเลิกเรียน",
  "menu.registrationSettings": "ตั้งค่าลงทะเบียน",
  "menu.courses": "คอร์สและโควต้า",
  "menu.externalParents": "ผู้ปกครองภายนอก",
  "menu.receipts": "ใบเสร็จ",
  "menu.eventManagement": "กิจกรรม/ทริป",
  "menu.eventImport": "นำเข้ากิจกรรม",
  "menu.paymentDeadlines": "กำหนดชำระ",
  "menu.registrationReports": "รายงานลงทะเบียน",
  "menu.summerActivities": "ซัมเมอร์แคมป์",
  "menu.import": "นำเข้าข้อมูล",
  "menu.registrationControl": "เปิด/ปิดลงทะเบียน",
  "menu.paymentReports": "รายงานการชำระ",
  "menu.discountManagement": "ส่วนลด",
  "menu.overview": "ภาพรวม",
  "menu.studentGroups": "กลุ่มนักเรียน",
  "menu.promotions": "ตั้งค่าส่วนลด",
  "menu.waiveFees": "ยกเว้นค่าธรรมเนียม",
  "menu.reports": "รายงาน",
  "menu.invoiceManagement": "ใบแจ้งหนี้",
  "menu.invoices": "รายการใบแจ้งหนี้",
  "menu.itemsTemplates": "รายการ / แม่แบบ",
  "menu.emailJobs": "ส่งอีเมล",
  "menu.studentList": "รายชื่อนักเรียน",
  "menu.tuitionByYear": "ค่าเทอมรายปี",
  "menu.users": "ผู้ใช้งาน",
  "menu.rolesPermissions": "สิทธิ์การใช้งาน",
  "menu.familyGroups": "ครอบครัว",
  "menu.studentManagement": "นักเรียน",
  "menu.userManagement": "ผู้ใช้งาน",

  // Common
  "common.save": "บันทึก",
  "common.cancel": "ยกเลิก",
  "common.edit": "แก้ไข",
  "common.delete": "ลบ",
  "common.add": "เพิ่ม",
  "common.search": "ค้นหา",
  "common.filter": "กรอง",
  "common.export": "ส่งออก",
  "common.import": "นำเข้า",
  "common.view": "ดู",
  "common.close": "ปิด",
  "common.confirm": "ยืนยัน",
  "common.back": "กลับ",
  "common.next": "ถัดไป",
  "common.submit": "ส่ง",
  "common.reset": "รีเซ็ต",
  "common.loading": "กำลังโหลด...",
  "common.noData": "ไม่มีข้อมูล",
  "common.all": "ทั้งหมด",
  "common.status": "สถานะ",
  "common.academicYear": "ปีการศึกษา",
  "common.allAcademicYears": "ทุกปีการศึกษา",
  "common.actions": "การดำเนินการ",
  "common.total": "รวม",
  "common.amount": "จำนวนเงิน",
  "common.date": "วันที่",
  "common.name": "ชื่อ",
  "common.email": "อีเมล",
  "common.phone": "โทรศัพท์",
  "common.address": "ที่อยู่",
  "common.description": "รายละเอียด",
  "common.notes": "หมายเหตุ",
  "common.type": "ประเภท",
  "common.yes": "ใช่",
  "common.no": "ไม่",
  "common.required": "จำเป็น",
  "common.optional": "ไม่บังคับ",
  "common.select": "เลือก",
  "common.selectAll": "เลือกทั้งหมด",
  "common.clear": "ล้าง",
  "common.clearFilters": "ล้างตัวกรอง",
  "common.refresh": "รีเฟรช",
  "common.print": "พิมพ์",
  "common.download": "ดาวน์โหลด",
  "common.upload": "อัปโหลด",
  "common.send": "ส่ง",
  "common.approve": "อนุมัติ",
  "common.reject": "ไม่อนุมัติ",
  "common.pending": "รอดำเนินการ",
  "common.approved": "อนุมัติแล้ว",
  "common.rejected": "ไม่อนุมัติ",
  "common.draft": "ฉบับร่าง",
  "common.sent": "ส่งแล้ว",
  "common.paid": "ชำระแล้ว",
  "common.unpaid": "ยังไม่ชำระ",
  "common.overdue": "เกินกำหนด",
  "common.cancelled": "ยกเลิก",
  "common.active": "ใช้งาน",
  "common.inactive": "ไม่ใช้งาน",
  "common.language": "ภาษา",
  "common.english": "English",
  "common.thai": "ไทย",

  // Dashboard
  "dashboard.title": "ภาพรวม",
  "dashboard.dataFilters": "ตัวกรองข้อมูล",
  "dashboard.filterDesc": "กรองข้อมูลค่าธรรมเนียมตามปีการศึกษา เทอม หรือช่วงวันที่",
  "dashboard.allData": "ข้อมูลทั้งหมด",
  "dashboard.filtered": "กรองโดย: ",
  "dashboard.filterOptions": "ตัวเลือกการกรอง",
  "dashboard.pickDateRange": "เลือกช่วงวันที่",
  "dashboard.quickActions": "ดำเนินการด่วน",
  "dashboard.last30Days": "30 วันที่ผ่านมา",
  "dashboard.thisYear": "ปีนี้",
  "dashboard.currentAcademicYear": "ปีการศึกษาปัจจุบัน",
  "dashboard.termOnly": "เฉพาะเทอม {term}",
  "dashboard.applyFilters": "ใช้ตัวกรอง",
  "dashboard.activeFilters": "ตัวกรองที่ใช้งานอยู่",
  "dashboard.studentsPaid": "นักเรียนที่ชำระเงินแล้ว",
  "dashboard.totalRevenue": "รายได้ทั้งหมด",
  "dashboard.yearlyPayments": "การชำระรายปี",
  "dashboard.termlyPayments": "การชำระรายเทอม",
  "dashboard.paymentTypeDistribution": "สัดส่วนประเภทการชำระเงิน",
  "dashboard.paymentChannels": "ช่องทางการชำระเงิน",
  "dashboard.revenueByTerm": "รายได้ตามเทอม",
  "dashboard.recentActivity": "ความเคลื่อนไหวการชำระเงินล่าสุด",
  "dashboard.yearly": "รายปี",
  "dashboard.termly": "รายเทอม",

  // Invoice Management
  "invoice.title": "จัดการใบแจ้งหนี้",
  "invoice.subtitle": "สร้างและจัดการใบแจ้งหนี้นักเรียน พร้อมแม่แบบและส่วนลด",
  "invoice.refreshed": "รีเฟรชรายการใบแจ้งหนี้แล้ว",
  "invoice.importExcel": "นำเข้า Excel",
  "invoice.exportReport": "ส่งออกรายงาน",
  "invoice.createInvoice": "สร้างใบแจ้งหนี้",
  "invoice.invoiceList": "รายการใบแจ้งหนี้",
  "invoice.invoiceNumber": "เลขที่ใบแจ้งหนี้",
  "invoice.studentName": "ชื่อนักเรียน",
  "invoice.studentId": "รหัสนักเรียน",
  "invoice.grade": "ชั้นเรียน",
  "invoice.room": "ห้อง",
  "invoice.term": "เทอม",
  "invoice.academicYear": "ปีการศึกษา",
  "invoice.issueDate": "วันที่ออก",
  "invoice.dueDate": "วันครบกำหนด",
  "invoice.subtotal": "ยอดรวมก่อนส่วนลด",
  "invoice.discount": "ส่วนลด",
  "invoice.netAmount": "ยอดสุทธิ",
  "invoice.finalAmount": "ยอดสุทธิสุดท้าย",
  "invoice.paymentStatus": "สถานะการชำระ",
  "invoice.pendingApproval": "รออนุมัติ",
  "invoice.viewInvoice": "ดูใบแจ้งหนี้",
  "invoice.editInvoice": "แก้ไขใบแจ้งหนี้",
  "invoice.deleteInvoice": "ลบใบแจ้งหนี้",
  "invoice.sendEmail": "ส่งอีเมล",
  "invoice.markAsPaid": "บันทึกการชำระเงิน",
  "invoice.printInvoice": "พิมพ์ใบแจ้งหนี้",
  "invoice.downloadPdf": "ดาวน์โหลด PDF",
  "invoice.invoiceDetails": "รายละเอียดใบแจ้งหนี้",
  "invoice.items": "รายการ",
  "invoice.quantity": "จำนวน",
  "invoice.unitPrice": "ราคาต่อหน่วย",
  "invoice.discountPercent": "ส่วนลด %",
  "invoice.discountAmount": "จำนวนส่วนลด",
  "invoice.totalAmount": "ยอดรวม",
  "invoice.paymentMethods": "วิธีการชำระเงิน",
  "invoice.bankTransfer": "โอนเงินผ่านธนาคาร",
  "invoice.creditCard": "บัตรเครดิต",
  "invoice.cash": "เงินสด",
  "invoice.cheque": "เช็ค",
  "invoice.billPayment": "ชำระผ่านเคาน์เตอร์",
  "invoice.latePaymentFee": "ค่าปรับชำระล่าช้า",
  "invoice.idCharges": "ค่าธรรมเนียม ID",
  "invoice.registrationFee": "ค่าลงทะเบียน",
  "invoice.applicationFee": "ค่าสมัคร",
  "invoice.securityDeposit": "เงินประกัน",
  "invoice.refundable": "คืนได้",
  "invoice.feeWaiver": "ยกเว้นค่าธรรมเนียม",
  "invoice.siblingDiscount": "ส่วนลดพี่น้อง",
  "invoice.staffChildDiscount": "ส่วนลดบุตรพนักงาน",
  "invoice.scholarship": "ทุนการศึกษา",
  "invoice.earlyBirdDiscount": "ส่วนลด Early Bird",
  "invoice.newStudent": "นักเรียนใหม่",
  "invoice.existingStudent": "นักเรียนปัจจุบัน",
  "invoice.selectStudent": "เลือกนักเรียน",
  "invoice.selectItems": "เลือกรายการ",
  "invoice.selectTemplate": "เลือกเทมเพลต",
  "invoice.paymentDeadline": "กำหนดชำระเงิน",
  "invoice.preview": "ตัวอย่าง",
  "invoice.saveAsDraft": "บันทึกเป็นฉบับร่าง",
  "invoice.createAndSend": "สร้างและส่ง",
  "invoice.approvalRequired": "ต้องการการอนุมัติ",
  "invoice.approvedBy": "อนุมัติโดย",
  "invoice.rejectedReason": "เหตุผลที่ไม่อนุมัติ",
  "invoice.invoiceNotes": "หมายเหตุใบแจ้งหนี้",
  "invoice.latePaymentPolicy": "ค่าปรับการชำระเงินล่าช้า 1.5% ต่อเดือนหรือส่วนของเดือน จะถูกคิดสำหรับการชำระเงินหลังวันครบกำหนด",
  "invoice.refundCondition": "เงื่อนไขการคืนเงินประกันเป็นไปตามข้อกำหนดและเงื่อนไขของโรงเรียน King's College International School Bangkok",
  "invoice.studentInvoices": "ใบแจ้งหนี้นักเรียน",
  "invoice.externalInvoices": "ใบแจ้งหนี้ภายนอก",
  "invoice.recipientName": "ชื่อผู้รับ",
  "invoice.recipientEmail": "อีเมลผู้รับ",
  "invoice.recipientAddress": "ที่อยู่ผู้รับ",
  "invoice.eventName": "ชื่อกิจกรรม",
  "invoice.external": "ภายนอก",
  "invoice.bulkActions": "ดำเนินการหลายรายการ",
  "invoice.selectedInvoices": "ใบแจ้งหนี้ที่เลือก",
  "invoice.approveSelected": "อนุมัติที่เลือก",
  "invoice.rejectSelected": "ไม่อนุมัติที่เลือก",
  "invoice.sendSelected": "ส่งที่เลือก",
  "invoice.exportSelected": "ส่งออกที่เลือก",
  "invoice.statistics": "สถิติ",
  "invoice.totalInvoices": "ใบแจ้งหนี้ทั้งหมด",
  "invoice.totalPending": "รออนุมัติ",
  "invoice.totalApproved": "อนุมัติแล้ว",
  "invoice.totalRejected": "ไม่อนุมัติ",
  "invoice.totalSent": "ส่งแล้ว",
  "invoice.totalPaid": "ชำระแล้ว",
  "invoice.totalOverdue": "เกินกำหนด",
  "invoice.totalRevenue": "รายได้รวม",
  "invoice.filterByStatus": "กรองตามสถานะ",
  "invoice.filterByGrade": "กรองตามชั้นเรียน",
  "invoice.filterByTerm": "กรองตามเทอม",
  "invoice.filterByDate": "กรองตามวันที่",
  "invoice.searchPlaceholder": "ค้นหาด้วยชื่อ, รหัส, หรือเลขที่ใบแจ้งหนี้...",
  "invoice.noInvoicesFound": "ไม่พบใบแจ้งหนี้",
  "invoice.createFirstInvoice": "สร้างใบแจ้งหนี้ใบแรก",
  "invoice.confirmApproval": "ยืนยันการอนุมัติ",
  "invoice.confirmApprovalMessage": "คุณแน่ใจหรือไม่ว่าต้องการอนุมัติใบแจ้งหนี้นี้?",
  "invoice.confirmRejection": "ยืนยันการไม่อนุมัติ",
  "invoice.confirmRejectionMessage": "กรุณาระบุเหตุผลที่ไม่อนุมัติใบแจ้งหนี้นี้",
  "invoice.rejectionReasonPlaceholder": "ระบุเหตุผลที่ไม่อนุมัติ...",
  "invoice.invoiceApproved": "อนุมัติใบแจ้งหนี้เรียบร้อย",
  "invoice.invoiceRejected": "ไม่อนุมัติใบแจ้งหนี้",
  "invoice.invoiceSent": "ส่งใบแจ้งหนี้เรียบร้อย",
  "invoice.invoiceDeleted": "ลบใบแจ้งหนี้แล้ว",
  "invoice.invoiceCreated": "สร้างใบแจ้งหนี้เสร็จสมบูรณ์",

  // After School
  "afterschool.title": "ภาพรวมกิจกรรมหลังเลิกเรียน",
  "afterschool.totalRegistrations": "จำนวนการลงทะเบียนทั้งหมด",
  "afterschool.activeActivities": "กิจกรรมที่เปิดสอน",
  "afterschool.averageAttendance": "อัตราการมาเรียนเฉลี่ย",
  "afterschool.registrationTrend": "แนวโน้มการลงทะเบียนและรายได้",
  "afterschool.activityPopularity": "ความนิยมของกิจกรรม",
  "afterschool.weeklyAttendance": "รูปแบบการเข้าเรียนรายสัปดาห์",
  "afterschool.revenueByActivity": "รายได้ตามกิจกรรม",
  "afterschool.capacityOverview": "ภาพรวมความจุ",
  "afterschool.recentRegistrations": "การลงทะเบียนล่าสุด",
  "afterschool.performanceAlerts": "การแจ้งเตือนประสิทธิภาพ",
  "afterschool.highDemand": "กิจกรรมที่มีความต้องการสูง",
  "afterschool.lowRegistration": "กิจกรรมที่มีการลงทะเบียนน้อย",
  "afterschool.topPerformers": "กิจกรรมที่ทำรายได้สูงสุด",
  "afterschool.utilization": "การใช้พื้นที่",
  "afterschool.enrolled": "ลงทะเบียนแล้ว",
  "afterschool.capacity": "ความจุ",

  // Activities
  "activity.swimming": "ว่ายน้ำ",
  "activity.football": "ฟุตบอล",
  "activity.artCraft": "ศิลปะและงานประดิษฐ์",
  "activity.music": "ดนตรี",
  "activity.basketball": "บาสเกตบอล",
  "activity.drama": "การแสดง",
  "activity.chess": "หมากรุก",
  "activity.coding": "เขียนโปรแกรม",
  "activity.swimmingPool": "สระว่ายน้ำ",
  "activity.footballField": "สนามฟุตบอล",
  "activity.artStudio": "สตูดิโอศิลปะ",
  "activity.musicRoom": "ห้องดนตรี",
  "activity.basketballCourt": "สนามบาสเกตบอล",
  "invoice.invoiceSaved": "บันทึกใบแจ้งหนี้เป็นฉบับร่าง",
  "invoice.fillRequiredFields": "กรุณากรอกข้อมูลที่จำเป็น",
  "invoice.selectAtLeastOneItem": "กรุณาเลือกอย่างน้อย 1 รายการ",
  "invoice.selectAtLeastOneStudent": "กรุณาเลือกนักเรียนอย่างน้อย 1 คน",
  "invoice.searchFilter": "ค้นหาและกรอง",
  "invoice.apply": "ใช้ตัวกรอง",
  "invoice.allYears": "ทุกปีการศึกษา",
  "invoice.allTerms": "ทุกเทอม",
  "invoice.yearGroup": "ชั้นเรียน",
  "invoice.allYearGroups": "ทุกชั้นเรียน",
  "invoice.allStatus": "ทุกสถานะ",
  "invoice.dateRange": "ช่วงวันที่",
  "invoice.fromDate": "ตั้งแต่",
  "invoice.toDate": "ถึง",
  "invoice.selectDate": "เลือกวันที่",
  "invoice.showingOf": "แสดง {count} จาก {total} รายการ",
  "invoice.showingRange": "แสดง {from} ถึง {to} จาก {total} รายการ",
  "invoice.show": "แสดง",
  "invoice.entries": "รายการ",
  "invoice.previous": "ก่อนหน้า",
  "invoice.next": "ถัดไป",
  "invoice.student": "นักเรียน",
  "invoice.recipient": "ผู้รับ",
  "invoice.event": "กิจกรรม",
  "invoice.noExternalInvoices": "ไม่มีใบแจ้งหนี้ภายนอก",
  "invoice.createExternalDesc": "สร้างใบแจ้งหนี้ภายนอกเพื่อเริ่มต้น",
  "invoice.recipientInfo": "ข้อมูลผู้รับ",
  "invoice.studentInfo": "ข้อมูลนักเรียน",
  "invoice.contactName": "ชื่อผู้ติดต่อ",
  "invoice.invoiceInfo": "รายละเอียดใบแจ้งหนี้",
  "invoice.invoiceDate": "วันที่ออกใบแจ้งหนี้",
  "invoice.schoolYear": "ปีการศึกษา",
  "invoice.viewOnly": "ดูอย่างเดียว",
  "invoice.description": "รายละเอียด",
  "invoice.newStudentFee": "ค่าธรรมเนียมนักเรียนใหม่",
  "invoice.siblingDiscountChild": "ส่วนลดพี่น้อง (บุตรคนที่ {order})",
  "invoice.registrationFeeWaiverTerm": "ยกเว้นค่าลงทะเบียน (฿{amount}/เทอม)",
  "invoice.securityDepositFeeWaiver": "ยกเว้นเงินประกัน",
  "invoice.idChargesPercent": "ค่าธรรมเนียม ID (3%)",
  "invoice.latePaymentFeePercent": "ค่าปรับชำระล่าช้า ({percent}%)",
  "invoice.paymentMethodsLabel": "วิธีการชำระเงิน:",
  "invoice.paymentMethodsList": "บัตรเครดิต, พร้อมเพย์, เคาน์เตอร์ธนาคาร, WeChat Pay, Alipay, เงินสด",
  "invoice.createNewInvoice": "สร้างใบแจ้งหนี้ใหม่",
  "invoice.createInvoiceDesc": "สร้างใบแจ้งหนี้โดยใช้เทมเพลตหรือรายการที่กำหนดเองสำหรับนักเรียน",
  "invoice.selectGrade": "เลือกชั้นเรียน",
  "invoice.chooseGradeLevel": "เลือกระดับชั้น",
  "invoice.availableItems": "รายการที่ใช้ได้สำหรับ {grade}",
  "invoice.grades": "ชั้น",
  "invoice.selectedItemsCount": "รายการที่เลือก ({count})",
  "invoice.clearAll": "ล้างทั้งหมด",
  "invoice.item": "รายการ",
  "invoice.category": "หมวดหมู่",
  "invoice.totalItems": "จำนวนรายการ",
  "invoice.students": "นักเรียน",
  "invoice.amountPerStudent": "ยอดต่อนักเรียน",
  "invoice.noItemsForGrade": "ไม่มีรายการสำหรับชั้นเรียนนี้",
  "invoice.contactAdminForItems": "กรุณาเลือกชั้นเรียนอื่นหรือติดต่อผู้ดูแลระบบเพื่อเพิ่มรายการ",
  "invoice.selectStudents": "เลือกนักเรียน",
  "invoice.individual": "รายบุคคล",
  "invoice.selectSpecificStudents": "เลือกนักเรียนเฉพาะราย",
  "invoice.csvUpload": "อัปโหลด CSV",
  "invoice.uploadStudentList": "อัปโหลดรายชื่อนักเรียน",
  "invoice.allStudents": "นักเรียนทั้งหมด",
  "invoice.selectEntireGrade": "เลือกทั้งชั้นเรียน",
  "invoice.searchByIdOrName": "ค้นหาด้วยรหัสหรือชื่อนักเรียน",
  "invoice.noStudentsFoundSearch": "ไม่พบนักเรียน",
  "invoice.uploadCsvDesc": "อัปโหลดไฟล์ CSV ที่มีข้อมูลนักเรียน",
  "invoice.fileUploaded": "อัปโหลดไฟล์แล้ว:",
  "invoice.loadedStudents": "โหลด {count} นักเรียน",
  "invoice.selectAllIn": "เลือกนักเรียนทั้งหมดใน {grade}",
  "invoice.studentsWillBeSelected": "{count} นักเรียนจะถูกเลือก",
  "invoice.selectAllStudentsBtn": "เลือกนักเรียนทั้งหมด",
  "invoice.selectedStudentsCount": "นักเรียนที่เลือก ({count})",
  "invoice.createInvoiceStep": "สร้างใบแจ้งหนี้",
  "invoice.invoiceSummary": "สรุปใบแจ้งหนี้",

  // Invoice Creation
  "invoiceCreate.title": "สร้างใบแจ้งหนี้",
  "invoiceCreate.step1": "เลือกปีการศึกษาและเทอม",
  "invoiceCreate.step2": "เลือกชั้นเรียนและห้อง",
  "invoiceCreate.step3": "เลือกนักเรียน",
  "invoiceCreate.step4": "เลือกรายการ",
  "invoiceCreate.step5": "กำหนดวันชำระเงิน",
  "invoiceCreate.step6": "ตรวจสอบและยืนยัน",
  "invoiceCreate.academicYear": "ปีการศึกษา",
  "invoiceCreate.selectAcademicYear": "เลือกปีการศึกษา",
  "invoiceCreate.term": "เทอม",
  "invoiceCreate.selectTerm": "เลือกเทอม",
  "invoiceCreate.grade": "ชั้นเรียน",
  "invoiceCreate.selectGrade": "เลือกชั้นเรียน",
  "invoiceCreate.room": "ห้อง",
  "invoiceCreate.selectRoom": "เลือกห้อง",
  "invoiceCreate.allRooms": "ทุกห้อง",
  "invoiceCreate.students": "นักเรียน",
  "invoiceCreate.selectedStudents": "นักเรียนที่เลือก",
  "invoiceCreate.noStudentsSelected": "ยังไม่ได้เลือกนักเรียน",
  "invoiceCreate.selectAllStudents": "เลือกนักเรียนทั้งหมด",
  "invoiceCreate.clearSelection": "ล้างการเลือก",
  "invoiceCreate.addNewStudent": "เพิ่มนักเรียนใหม่",
  "invoiceCreate.importFromCsv": "นำเข้าจาก CSV",
  "invoiceCreate.items": "รายการ",
  "invoiceCreate.selectedItems": "รายการที่เลือก",
  "invoiceCreate.noItemsSelected": "ยังไม่ได้เลือกรายการ",
  "invoiceCreate.addItem": "เพิ่มรายการ",
  "invoiceCreate.removeItem": "ลบรายการ",
  "invoiceCreate.itemName": "ชื่อรายการ",
  "invoiceCreate.itemDescription": "รายละเอียด",
  "invoiceCreate.itemAmount": "จำนวนเงิน",
  "invoiceCreate.template": "เทมเพลต",
  "invoiceCreate.selectTemplate": "เลือกเทมเพลต",
  "invoiceCreate.noTemplate": "ไม่ใช้เทมเพลต",
  "invoiceCreate.paymentDeadline": "กำหนดชำระเงิน",
  "invoiceCreate.selectDate": "เลือกวันที่",
  "invoiceCreate.preview": "ตัวอย่างใบแจ้งหนี้",
  "invoiceCreate.previewDescription": "ตรวจสอบรายละเอียดก่อนสร้างใบแจ้งหนี้",
  "invoiceCreate.billTo": "เรียกเก็บจาก",
  "invoiceCreate.invoiceInfo": "ข้อมูลใบแจ้งหนี้",
  "invoiceCreate.itemsAndFees": "รายการและค่าธรรมเนียม",
  "invoiceCreate.discounts": "ส่วนลด",
  "invoiceCreate.summary": "สรุป",
  "invoiceCreate.submitForApproval": "ส่งเพื่อขออนุมัติ",
  "invoiceCreate.createAndSendEmail": "สร้างและส่งอีเมล",
  "invoiceCreate.backToEdit": "กลับไปแก้ไข",
  "invoiceCreate.confirmCreate": "ยืนยันการสร้าง",
  "invoiceCreate.invoicePreview": "ตัวอย่างใบแจ้งหนี้",
  "invoiceCreate.studentInfo": "ข้อมูลนักเรียน",
  "invoiceCreate.parentInfo": "ข้อมูลผู้ปกครอง",
  "invoiceCreate.parentName": "ชื่อผู้ปกครอง",
  "invoiceCreate.parentEmail": "อีเมลผู้ปกครอง",
  "invoiceCreate.parentPhone": "โทรศัพท์ผู้ปกครอง",
  "invoiceCreate.registrationFees": "ค่าธรรมเนียมลงทะเบียน",
  "invoiceCreate.registrationFeesNote": "ค่าธรรมเนียมต่อไปนี้จะถูกคิดโดยอัตโนมัติสำหรับนักเรียนใหม่:",
  "invoiceCreate.idChargesNote": "ค่าธรรมเนียม ID (3%) จะถูกคำนวณโดยอัตโนมัติ",
  "invoiceCreate.latePaymentNote": "ค่าปรับชำระล่าช้าจะถูกคิดหลังวันครบกำหนด",
  "invoiceCreate.externalInvoice": "ใบแจ้งหนี้ภายนอก",
  "invoiceCreate.externalInvoiceDescription": "สร้างใบแจ้งหนี้สำหรับผู้รับภายนอก (ไม่ใช่นักเรียน)",
  "invoiceCreate.recipientDetails": "รายละเอียดผู้รับ",
  "invoiceCreate.firstName": "ชื่อ",
  "invoiceCreate.lastName": "นามสกุล",
  "invoiceCreate.nickname": "ชื่อเล่น",
  "invoiceCreate.gender": "เพศ",
  "invoiceCreate.male": "ชาย",
  "invoiceCreate.female": "หญิง",
  "invoiceCreate.dateOfBirth": "วันเกิด",
  "invoiceCreate.familyType": "ประเภทครอบครัว",
  "invoiceCreate.createNewFamily": "สร้างครอบครัวใหม่",
  "invoiceCreate.joinExistingFamily": "เข้าร่วมครอบครัวที่มีอยู่ (พี่น้อง)",
  "invoiceCreate.selectFamily": "เลือกครอบครัว",
  "invoiceCreate.childOrder": "ลำดับบุตร",
  "invoiceCreate.parentGuardianInfo": "ข้อมูลผู้ปกครอง",
  "invoiceCreate.parentGuardianName": "ชื่อผู้ปกครอง",
  "invoiceCreate.relationship": "ความสัมพันธ์",
  "invoiceCreate.father": "บิดา",
  "invoiceCreate.mother": "มารดา",
  "invoiceCreate.guardian": "ผู้ปกครอง",
  "invoiceCreate.other": "อื่นๆ",
  "invoiceCreate.amountInWords": "จำนวนเงินเป็นตัวอักษร",

  // Student List
  "student.title": "รายชื่อนักเรียน",
  "student.description": "จัดการข้อมูลนักเรียนและการลงทะเบียน",
  "student.addStudent": "เพิ่มนักเรียน",
  "student.editStudent": "แก้ไขนักเรียน",
  "student.deleteStudent": "ลบนักเรียน",
  "student.viewStudent": "ดูข้อมูลนักเรียน",
  "student.promoteGrade": "เลื่อนชั้น",
  "student.families": "ครอบครัว",
  "student.studentDetails": "รายละเอียดนักเรียน",
  "student.personalInfo": "ข้อมูลส่วนตัว",
  "student.academicInfo": "ข้อมูลการศึกษา",
  "student.familyInfo": "ข้อมูลครอบครัว",
  "student.contactInfo": "ข้อมูลติดต่อ",
  "student.firstName": "ชื่อ",
  "student.lastName": "นามสกุล",
  "student.nickname": "ชื่อเล่น",
  "student.gender": "เพศ",
  "student.dateOfBirth": "วันเกิด",
  "student.studentId": "รหัสนักเรียน",
  "student.grade": "ชั้นเรียน",
  "student.room": "ห้อง",
  "student.academicYear": "ปีการศึกษา",
  "student.enrollmentDate": "วันที่เข้าเรียน",
  "student.enrollmentTerm": "เทอมที่เข้าเรียน",
  "student.status": "สถานะ",
  "student.familyId": "รหัสครอบครัว",
  "student.childOrder": "ลำดับบุตร",
  "student.parents": "ผู้ปกครอง",
  "student.parentName": "ชื่อผู้ปกครอง",
  "student.parentEmail": "อีเมลผู้ปกครอง",
  "student.parentPhone": "โทรศัพท์ผู้ปกครอง",
  "student.relationship": "ความสัมพันธ์",
  "student.notes": "หมายเหตุ",
  "student.createdAt": "สร้างเมื่อ",
  "student.updatedAt": "อัปเดตเมื่อ",
  "student.searchPlaceholder": "ค้นหาด้วยชื่อหรือรหัสนักเรียน...",
  "student.filterByGrade": "กรองตามชั้นเรียน",
  "student.filterByStatus": "กรองตามสถานะ",
  "student.noStudentsFound": "ไม่พบนักเรียน",
  "student.totalStudents": "นักเรียนทั้งหมด",
  "student.activeStudents": "นักเรียนปัจจุบัน",
  "student.inactiveStudents": "นักเรียนที่ไม่ได้ใช้งาน",
  "student.newStudents": "นักเรียนใหม่",
  "student.importStudents": "นำเข้านักเรียน",
  "student.exportStudents": "ส่งออกนักเรียน",
  "student.confirmDelete": "คุณแน่ใจหรือไม่ว่าต้องการลบนักเรียนนี้?",
  "student.deleteWarning": "การดำเนินการนี้ไม่สามารถย้อนกลับได้",
  "student.studentAdded": "เพิ่มนักเรียนเรียบร้อย",
  "student.studentUpdated": "อัปเดตนักเรียนเรียบร้อย",
  "student.studentDeleted": "ลบนักเรียนเรียบร้อย",

  // Item Management
  "item.title": "รายการ / เทมเพลต",
  "item.items": "รายการ",
  "item.templates": "เทมเพลต",
  "item.chooseInvoiceType": "เลือกประเภทใบแจ้งหนี้ที่ต้องการสร้าง",
  "item.applicationRegFees": "ค่าสมัครและค่าลงทะเบียน",
  "item.configureInitialCharges": "กำหนดค่าใช้จ่ายเริ่มต้นสำหรับผู้สมัครใหม่",
  "item.feeType": "ประเภทค่าธรรมเนียม",
  "item.amountTHB": "จำนวนเงิน (บาท)",
  "item.refundable": "คืนเงินได้",
  "item.addItem": "เพิ่มรายการ",
  "item.editItem": "แก้ไขรายการ",
  "item.deleteItem": "ลบรายการ",
  "item.itemName": "ชื่อรายการ",
  "item.itemCode": "รหัสรายการ",
  "item.category": "หมวดหมู่",
  "item.amount": "จำนวนเงิน",
  "item.description": "รายละเอียด",
  "item.isActive": "ใช้งาน",
  "item.addTemplate": "เพิ่มเทมเพลต",
  "item.editTemplate": "แก้ไขเทมเพลต",
  "item.deleteTemplate": "ลบเทมเพลต",
  "item.templateName": "ชื่อเทมเพลต",
  "item.templateItems": "รายการในเทมเพลต",
  "item.totalAmount": "ยอดรวม",
  "item.itemsCount": "จำนวนรายการ",
  "item.noItemsFound": "ไม่พบรายการ",
  "item.noTemplatesFound": "ไม่พบเทมเพลต",
  "item.searchItems": "ค้นหารายการ...",
  "item.searchTemplates": "ค้นหาเทมเพลต...",
  "item.filterByCategory": "กรองตามหมวดหมู่",
  "item.tuition": "ค่าเล่าเรียน",
  "item.activities": "กิจกรรม",
  "item.transportation": "ค่าเดินทาง",
  "item.meals": "ค่าอาหาร",
  "item.uniform": "เครื่องแบบ",
  "item.books": "หนังสือ",
  "item.events": "กิจกรรมพิเศษ",
  "item.others": "อื่นๆ",
  "item.itemAdded": "เพิ่มรายการเรียบร้อย",
  "item.itemUpdated": "อัปเดตรายการเรียบร้อย",
  "item.itemDeleted": "ลบรายการเรียบร้อย",
  "item.templateAdded": "เพิ่มเทมเพลตเรียบร้อย",
  "item.templateUpdated": "อัปเดตเทมเพลตเรียบร้อย",
  "item.templateDeleted": "ลบเทมเพลตเรียบร้อย",
  "item.confirmDeleteItem": "คุณแน่ใจหรือไม่ว่าต้องการลบรายการนี้?",
  "item.confirmDeleteTemplate": "คุณแน่ใจหรือไม่ว่าต้องการลบเทมเพลตนี้?",

  // Discount Management
  "discount.title": "จัดการส่วนลด",
  "discount.subtitle": "จัดการรหัสส่วนลดและวิเคราะห์ประสิทธิภาพส่วนลด",
  "discount.overview": "ภาพรวม",
  "discount.studentGroups": "กลุ่มนักเรียน",
  "discount.promotions": "โปรโมชั่น",
  "discount.waiveFees": "ยกเว้นค่าธรรมเนียม",
  "discount.reports": "รายงาน",
  "discount.addDiscount": "เพิ่มส่วนลด",
  "discount.editDiscount": "แก้ไขส่วนลด",
  "discount.deleteDiscount": "ลบส่วนลด",
  "discount.discountName": "ชื่อส่วนลด",
  "discount.discountType": "ประเภทส่วนลด",
  "discount.percentage": "เปอร์เซ็นต์",
  "discount.fixedAmount": "จำนวนคงที่",
  "discount.discountValue": "มูลค่าส่วนลด",
  "discount.applicableTo": "ใช้ได้กับ",
  "discount.startDate": "วันเริ่มต้น",
  "discount.endDate": "วันสิ้นสุด",
  "discount.isActive": "ใช้งาน",
  "discount.conditions": "เงื่อนไข",
  "discount.siblingDiscount": "ส่วนลดพี่น้อง",
  "discount.staffChildDiscount": "ส่วนลดบุตรพนักงาน",
  "discount.scholarshipDiscount": "ทุนการศึกษา",
  "discount.earlyBirdDiscount": "ส่วนลด Early Bird",
  "discount.feeWaiver": "ยกเว้นค่าธรรมเนียม",
  "discount.feeWaiverProgram": "โครงการยกเว้นค่าธรรมเนียม",
  "discount.feeWaiverDescription": "ยกเว้นค่าธรรมเนียมสำหรับนักเรียนที่เรียนครบ 3 ปีขึ้นไป (บุตรคนที่ 2 เป็นต้นไป)",
  "discount.registrationFeeWaiver": "ยกเว้นค่าลงทะเบียน",
  "discount.securityDepositWaiver": "ยกเว้นเงินประกัน",
  "discount.eligibility": "คุณสมบัติ",
  "discount.creditPerTerm": "เครดิตต่อเทอม",
  "discount.termsRemaining": "เทอมที่เหลือ",
  "discount.totalCredit": "เครดิตทั้งหมด",
  "discount.noDiscountsFound": "ไม่พบส่วนลด",
  "discount.discountAdded": "เพิ่มส่วนลดเรียบร้อย",
  "discount.discountUpdated": "อัปเดตส่วนลดเรียบร้อย",
  "discount.discountDeleted": "ลบส่วนลดเรียบร้อย",

  // Discount Options
  "discountOptions.title": "ตัวเลือกส่วนลด",
  "discountOptions.subtitle": "ตั้งค่าส่วนลดพี่น้อง ค่าปรับชำระล่าช้า และสิทธิพิเศษค่าลงทะเบียน",
  "discountOptions.saveAllChanges": "บันทึกการเปลี่ยนแปลงทั้งหมด",
  "discountOptions.siblingDiscounts": "ส่วนลดพี่น้อง",
  "discountOptions.siblingDiscountsDesc": "พี่น้องที่เรียนในโรงเรียนพร้อมกันมีสิทธิ์รับส่วนลดค่าเล่าเรียน ในกรณีที่พี่คนโตจบการศึกษาปลาย Year 13 น้องๆ จะยังคงสิทธิ์พี่น้องไว้",
  "discountOptions.enabled": "เปิดใช้งาน",
  "discountOptions.childOrder": "ลำดับบุตร",
  "discountOptions.discountPercentage": "เปอร์เซ็นต์ส่วนลด",
  "discountOptions.preview": "ตัวอย่าง",
  "discountOptions.off": "ลด",
  "discountOptions.noDiscount": "ไม่มีส่วนลด",
  "discountOptions.confirmSaveChanges": "ยืนยันการบันทึก",
  "discountOptions.confirmSaveDesc": "คุณแน่ใจหรือไม่ว่าต้องการบันทึกตัวเลือกส่วนลดทั้งหมดสำหรับปีการศึกษา {year}?",
  "discountOptions.configured": "ตั้งค่าแล้ว",
  "discountOptions.latePayment": "ชำระล่าช้า",
  "discountOptions.disabled": "ปิดใช้งาน",
  "discountOptions.perMonth": "ต่อเดือน",
  "discountOptions.perWeek": "ต่อสัปดาห์",
  "discountOptions.totalInitialFees": "ค่าธรรมเนียมเริ่มต้นรวม",
  "discountOptions.confirmSave": "ยืนยันการบันทึก",
  "discountOptions.savedSuccess": "บันทึกตัวเลือกส่วนลดสำหรับ {year} แล้ว",
  "discountOptions.feesAndTuition": "ข้อมูลค่าธรรมเนียมและค่าเล่าเรียน - ปีการศึกษา {year}",
  "discountOptions.firstChild": "บุตรคนแรก",
  "discountOptions.secondChild": "บุตรคนที่สอง",
  "discountOptions.thirdChild": "บุตรคนที่สาม",
  "discountOptions.fourthChild": "บุตรคนที่สี่",
  "discountOptions.fifthChild": "บุตรคนที่ห้าและต่อๆ ไป",
  "discountOptions.academicYear": "ปีการศึกษา",
  "discountOptions.selectYear": "เลือกปี",
  "discountOptions.schoolName": "โรงเรียนนานาชาติคิงส์คอลเลจ กรุงเทพฯ",
  "discountOptions.feesInfo": "ข้อมูลค่าธรรมเนียมและค่าเล่าเรียน - ปีการศึกษา {year}",
  "discountOptions.confirmSaveTitle": "ยืนยันการบันทึกการเปลี่ยนแปลง",
  "discountOptions.confirmSaveMessage": "คุณแน่ใจหรือไม่ว่าต้องการบันทึกตัวเลือกส่วนลดทั้งหมดสำหรับปีการศึกษา {year}?",
  "discountOptions.per": "ต่อ",
  "discountOptions.month": "เดือน",
  "discountOptions.week": "สัปดาห์",
  "discountOptions.percentOff": "ลด {percent}%",
  "discountOptions.cancel": "ยกเลิก",

  // Discount Reports
  "discountReports.title": "รายงานส่วนลด",
  "discountReports.subtitle": "ดูรายละเอียดส่วนลดนักเรียนและสร้างรายงาน",
  "discountReports.exportCsv": "ส่งออก CSV",
  "discountReports.totalStudents": "นักเรียนทั้งหมด",
  "discountReports.withDiscountsApplied": "ที่ได้รับส่วนลด",
  "discountReports.totalDiscount": "ส่วนลดรวม",
  "discountReports.totalSavingsProvided": "ยอดประหยัดทั้งหมด",
  "discountReports.averageDiscount": "ส่วนลดเฉลี่ย",
  "discountReports.avgPercentageDiscount": "เปอร์เซ็นต์ส่วนลดเฉลี่ย",
  "discountReports.yearGroups": "ชั้นปี",
  "discountReports.withDiscountStudents": "ที่มีนักเรียนรับส่วนลด",
  "discountReports.searchFilter": "ค้นหาและกรอง",
  "discountReports.apply": "ใช้งาน",
  "discountReports.clear": "ล้าง",
  "discountReports.search": "ค้นหา",
  "discountReports.nameOrId": "ชื่อหรือรหัส...",
  "discountReports.yearGroup": "ชั้นปี",
  "discountReports.allYearGroups": "ทุกชั้นปี",
  "discountReports.discountType": "ประเภทส่วนลด",
  "discountReports.allTypes": "ทุกประเภท",
  "discountReports.sibling": "พี่น้อง",
  "discountReports.scholarship": "ทุนการศึกษา",
  "discountReports.staff": "บุตรพนักงาน",
  "discountReports.earlyBird": "Early Bird",
  "discountReports.group": "กลุ่ม",
  "discountReports.campaign": "แคมเปญ",
  "discountReports.feeWaiver": "ยกเว้นค่าธรรมเนียม",
  "discountReports.status": "สถานะ",
  "discountReports.allStatus": "ทุกสถานะ",
  "discountReports.active": "ใช้งาน",
  "discountReports.pending": "รอดำเนินการ",
  "discountReports.expired": "หมดอายุ",
  "discountReports.studentDiscountDetails": "รายละเอียดส่วนลดนักเรียน",
  "discountReports.showingOf": "แสดง {shown} จาก {total} คน",
  "discountReports.studentId": "รหัสนักเรียน",
  "discountReports.studentName": "ชื่อนักเรียน",
  "discountReports.parent": "ผู้ปกครอง",
  "discountReports.discountTypes": "ประเภทส่วนลด",
  "discountReports.discountsDetail": "รายละเอียดส่วนลด",
  "discountReports.amount": "จำนวนเงิน",
  "discountReports.discount": "ส่วนลด",
  "discountReports.net": "สุทธิ",
  "discountReports.appliedTo": "ใช้กับ",
  "discountReports.noStudentsFound": "ไม่พบนักเรียนตามเงื่อนไขการกรอง",
  "discountReports.discountByType": "ส่วนลดตามประเภท",
  "discountReports.breakdownByCategory": "รายละเอียดส่วนลดแยกตามประเภท",
  "discountReports.students": "คน",
  "discountReports.discountByYearGroup": "ส่วนลดตามชั้นปี",
  "discountReports.breakdownByYearGroup": "รายละเอียดส่วนลดแยกตามชั้นปี",

  // Waive Fee Management
  "waiveFee.title": "แดชบอร์ดจัดการยกเว้นค่าธรรมเนียม",
  "waiveFee.subtitle": "ติดตามและจัดการส่วนลดพี่น้องข้ามปีการศึกษา",
  "waiveFee.exportData": "ส่งออกข้อมูล",
  "waiveFee.importCsv": "นำเข้า CSV",
  "waiveFee.academicYear": "ปีการศึกษา",
  "waiveFee.reset": "รีเซ็ต",
  "waiveFee.totalStudents": "นักเรียนทั้งหมด",
  "waiveFee.receivingWaivers": "ได้รับยกเว้นค่าธรรมเนียมใน {year}",
  "waiveFee.totalFamilies": "ครอบครัวทั้งหมด",
  "waiveFee.familiesBenefiting": "ครอบครัวที่ได้รับประโยชน์จากการยกเว้น",
  "waiveFee.totalWaiverAmount": "ยอดยกเว้นรวม",
  "waiveFee.totalWaiversFor": "ยอดยกเว้นทั้งหมดสำหรับ {year}",
  "waiveFee.averagePerFamily": "เฉลี่ยต่อครอบครัว",
  "waiveFee.avgWaiverPerFamily": "ยอดยกเว้นเฉลี่ยต่อครอบครัว",
  "waiveFee.registrationFeeWaiverProgram": "โปรแกรมยกเว้นค่าลงทะเบียน",
  "waiveFee.configureWaiver": "ตั้งค่าเงื่อนไขการยกเว้นและการแจกจ่ายเครดิต",
  "waiveFee.minYearGroup": "ชั้นปีขั้นต่ำ",
  "waiveFee.minTerms1stChild": "เทอมขั้นต่ำ (บุตรคนแรก)",
  "waiveFee.creditAmountThb": "จำนวนเครดิต (บาท)",
  "waiveFee.termsToCredit": "จำนวนเทอมที่ให้เครดิต",
  "waiveFee.firstChildPrivilege": "บุตรคนแรกได้สิทธิ์ทันที",
  "waiveFee.skipMinTerms": "ข้ามเงื่อนไขเทอมขั้นต่ำสำหรับบุตรคนแรก",
  "waiveFee.eligibilitySummary": "สรุปคุณสมบัติ",
  "waiveFee.yearPlusStudents": "นักเรียน Year {year}+",
  "waiveFee.firstChildImmediate": "บุตรคนแรก: ทันที",
  "waiveFee.firstChildAfterTerms": "บุตรคนแรก: หลัง {terms} เทอม",
  "waiveFee.secondChildImmediate": "บุตรคนที่ 2+: ทันทีตั้งแต่ Year {year}",
  "waiveFee.creditPerTerm": "เครดิต: {amount}/เทอม x {terms} เทอม",
  "waiveFee.multiYearSummary": "ตารางสรุปยกเว้นหลายปี",
  "waiveFee.avgWaiverAcrossYears": "ยอดยกเว้นเฉลี่ยต่อนักเรียนในทุกปีการศึกษาและเทอม",
  "waiveFee.term": "เทอม {num}",
  "waiveFee.viewMore": "ดูเพิ่มเติม",
  "waiveFee.studentsCount": "{count} คน",
  "waiveFee.familiesCount": "{count} ครอบครัว",
  "waiveFee.olderSibling": "พี่",
  "waiveFee.youngerSibling": "น้อง",
  "waiveFee.yearTotal": "รวมทั้งปี",
  "waiveFee.total": "รวม",
  "waiveFee.noteValues": "ค่าที่แสดงคือยอดยกเว้นเฉลี่ยต่อนักเรียน Year 1-3: น้องได้รับส่วนลด Year 4-6: พี่ได้รับส่วนลด แต่ละช่องแสดง: ยอดเฉลี่ย / จำนวนนักเรียน / จำนวนครอบครัว / การกระจายพี่น้อง",
  "waiveFee.active": "ใช้งาน",
  "waiveFee.completed": "เสร็จสิ้น",
  "waiveFee.pending": "รอดำเนินการ",

  // Family Groups
  "familyGroups.title": "กลุ่มครอบครัว",
  "familyGroups.subtitle": "จัดการกลุ่มครอบครัวและความสัมพันธ์พี่น้องสำหรับการคำนวณส่วนลด",
  "familyGroups.addFamily": "เพิ่มครอบครัว",
  "familyGroups.totalFamilies": "ครอบครัวทั้งหมด",
  "familyGroups.studentsInFamilies": "นักเรียนในครอบครัว",
  "familyGroups.multiChildFamilies": "ครอบครัวที่มีบุตรหลายคน",
  "familyGroups.studentsWithDiscount": "นักเรียนที่ได้รับส่วนลด",
  "familyGroups.searchFamilies": "ค้นหาครอบครัว...",
  "familyGroups.noFamiliesFound": "ไม่พบครอบครัว สร้างครอบครัวเพื่อจัดกลุ่มพี่น้อง",
  "familyGroups.family": "ครอบครัว",
  "familyGroups.children": "บุตร",
  "familyGroups.noAddressProvided": "ไม่มีที่อยู่",
  "familyGroups.totalDiscount": "รวม: ส่วนลด {percent}%",
  "familyGroups.noStudentsInFamily": "ยังไม่มีนักเรียนในครอบครัวนี้ เพิ่มนักเรียนเพื่อคำนวณส่วนลดพี่น้อง",
  "familyGroups.order": "ลำดับ",
  "familyGroups.student": "นักเรียน",
  "familyGroups.studentId": "รหัสนักเรียน",
  "familyGroups.yearGroup": "ชั้นปี",
  "familyGroups.siblingDiscount": "ส่วนลดพี่น้อง",
  "familyGroups.feeWaiver": "ยกเว้นค่าธรรมเนียม",
  "familyGroups.actions": "การดำเนินการ",
  "familyGroups.off": "% ลด",
  "familyGroups.noDiscount": "ไม่มีส่วนลด",
  "familyGroups.remove": "ลบ",
  "familyGroups.siblingDiscountSummary": "สรุปส่วนลดพี่น้อง",
  "familyGroups.discountLabel": "ส่วนลด {percent}%",
  "familyGroups.registrationFeeWaiverProgram": "โปรแกรมยกเว้นค่าลงทะเบียน",
  "familyGroups.perTerm": "/เทอม",
  "familyGroups.pending": "รอดำเนินการ",
  "familyGroups.show": "แสดง",
  "familyGroups.entries": "รายการ",
  "familyGroups.showingOf": "แสดง {from} ถึง {to} จาก {total} ครอบครัว",
  "familyGroups.previous": "ก่อนหน้า",
  "familyGroups.next": "ถัดไป",
  "familyGroups.studentsNotAssigned": "นักเรียนที่ยังไม่ได้อยู่ในครอบครัว",
  "familyGroups.notAssignedDesc": "นักเรียนเหล่านี้ยังไม่ได้อยู่ในกลุ่มครอบครัวใดและจะไม่ได้รับส่วนลดพี่น้อง",
  "familyGroups.more": "+{count} เพิ่มเติม",
  "familyGroups.createNewFamily": "สร้างครอบครัวใหม่",
  "familyGroups.editFamily": "แก้ไขครอบครัว",
  "familyGroups.deleteFamily": "ลบครอบครัว",
  "familyGroups.familyCode": "รหัสครอบครัว",
  "familyGroups.familyName": "ชื่อครอบครัว",
  "familyGroups.address": "ที่อยู่",
  "familyGroups.email": "อีเมล",
  "familyGroups.emailForInvoices": "อีเมล (สำหรับใบแจ้งหนี้)",
  "familyGroups.phone": "โทรศัพท์",
  "familyGroups.cancel": "ยกเลิก",
  "familyGroups.createFamily": "สร้างครอบครัว",
  "familyGroups.saveChanges": "บันทึกการเปลี่ยนแปลง",
  "familyGroups.confirmDeleteFamily": "คุณแน่ใจหรือไม่ว่าต้องการลบครอบครัว {name}?",
  "familyGroups.deleteWarning": "นักเรียนทุกคนในครอบครัวนี้จะถูกลบออกจากกลุ่มครอบครัวและจะสูญเสียส่วนลดพี่น้อง",
  "familyGroups.addStudentTo": "เพิ่มนักเรียนเข้าครอบครัว {name}",
  "familyGroups.allStudentsAssigned": "นักเรียนทุกคนถูกจัดเข้าครอบครัวแล้ว",
  "familyGroups.selectStudent": "เลือกนักเรียน",
  "familyGroups.selectAStudent": "เลือกนักเรียน",
  "familyGroups.willBeAddedAsChild": "นักเรียนจะถูกเพิ่มเป็นบุตรคนที่ #{num}",
  "familyGroups.addToFamily": "เพิ่มเข้าครอบครัว",
  "familyGroups.familyCreated": "สร้างครอบครัวเรียบร้อย",
  "familyGroups.familyUpdated": "อัปเดตครอบครัวเรียบร้อย",
  "familyGroups.familyDeleted": "ลบครอบครัวเรียบร้อย",
  "familyGroups.studentAdded": "เพิ่มนักเรียนเข้าครอบครัวแล้ว",
  "familyGroups.studentRemoved": "ลบนักเรียนออกจากครอบครัวแล้ว",

  // Messages & Notifications
  "message.success": "สำเร็จ",
  "message.error": "ข้อผิดพลาด",
  "message.warning": "คำเตือน",
  "message.info": "ข้อมูล",
  "message.confirm": "ยืนยัน",
  "message.areYouSure": "คุณแน่ใจหรือไม่?",
  "message.actionCannotBeUndone": "การดำเนินการนี้ไม่สามารถย้อนกลับได้",
  "message.savedSuccessfully": "บันทึกเรียบร้อย",
  "message.deletedSuccessfully": "ลบเรียบร้อย",
  "message.updatedSuccessfully": "อัปเดตเรียบร้อย",
  "message.createdSuccessfully": "สร้างเรียบร้อย",
  "message.sentSuccessfully": "ส่งเรียบร้อย",
  "message.operationFailed": "การดำเนินการล้มเหลว",
  "message.pleaseWait": "กรุณารอสักครู่...",
  "message.processingRequest": "กำลังประมวลผล...",
  "message.noResultsFound": "ไม่พบผลลัพธ์",
  "message.tryDifferentSearch": "ลองค้นหาด้วยคำอื่น",

  // Validation
  "validation.required": "จำเป็นต้องกรอก",
  "validation.invalidEmail": "อีเมลไม่ถูกต้อง",
  "validation.invalidPhone": "เบอร์โทรศัพท์ไม่ถูกต้อง",
  "validation.minLength": "ต้องมีอย่างน้อย {min} ตัวอักษร",
  "validation.maxLength": "ต้องไม่เกิน {max} ตัวอักษร",
  "validation.minValue": "ค่าต่ำสุดคือ {min}",
  "validation.maxValue": "ค่าสูงสุดคือ {max}",
  "validation.invalidDate": "วันที่ไม่ถูกต้อง",
  "validation.dateInPast": "วันที่ต้องเป็นอดีต",
  "validation.dateInFuture": "วันที่ต้องเป็นอนาคต",
  "validation.passwordMismatch": "รหัสผ่านไม่ตรงกัน",
  "validation.invalidFormat": "รูปแบบไม่ถูกต้อง",

  // Date & Time
  "date.today": "วันนี้",
  "date.yesterday": "เมื่อวาน",
  "date.tomorrow": "พรุ่งนี้",
  "date.thisWeek": "สัปดาห์นี้",
  "date.lastWeek": "สัปดาห์ที่แล้ว",
  "date.thisMonth": "เดือนนี้",
  "date.lastMonth": "เดือนที่แล้ว",
  "date.thisYear": "ปีนี้",
  "date.lastYear": "ปีที่แล้ว",
  "date.custom": "กำหนดเอง",
  "date.from": "จาก",
  "date.to": "ถึง",

  // Roles & Permissions
  "roles.title": "บทบาทและสิทธิ์",
  "roles.subtitle": "จัดการบทบาทผู้ใช้และสิทธิ์การเข้าถึง",
  "roles.addRole": "เพิ่มบทบาท",
  "roles.editRole": "แก้ไขบทบาท",
  "roles.deleteRole": "ลบบทบาท",
  "roles.roleName": "ชื่อบทบาท",
  "roles.description": "คำอธิบาย",
  "roles.permissions": "สิทธิ์",
  "roles.users": "ผู้ใช้",
  "roles.assignedUsers": "ผู้ใช้ที่กำหนด",
  "roles.roleDetails": "รายละเอียดบทบาท",
  "roles.permissionModules": "โมดูลสิทธิ์",
  "roles.selectAll": "เลือกทั้งหมด",
  "roles.noRolesFound": "ไม่พบบทบาท",
  "roles.roleCreated": "สร้างบทบาทเรียบร้อย",
  "roles.roleUpdated": "อัปเดตบทบาทเรียบร้อย",
  "roles.roleDeleted": "ลบบทบาทเรียบร้อย",
  "roles.cannotDeleteDefault": "ไม่สามารถลบบทบาทเริ่มต้นของระบบ",
  "roles.view": "ดู",
  "roles.create": "สร้าง",
  "roles.edit": "แก้ไข",
  "roles.delete": "ลบ",
  "roles.manage": "จัดการ",
  "roles.export": "ส่งออก",
  "roles.void": "ยกเลิก",
  "roles.sendEmail": "ส่งอีเมล",
  "roles.download": "ดาวน์โหลด",
  "roles.createNewRole": "สร้างบทบาทใหม่",
  "roles.createNewRoleDesc": "กำหนดบทบาทใหม่พร้อมสิทธิ์เฉพาะ",
  "roles.editRoleInfo": "แก้ไขข้อมูลบทบาทและสิทธิ์",
  "roles.roleNamePlaceholder": "ระบุชื่อบทบาท",
  "roles.descriptionPlaceholder": "ระบุคำอธิบายบทบาท",

  // User Management
  "users.title": "จัดการผู้ใช้",
  "users.subtitle": "จัดการบัญชีผู้ใช้และการเข้าถึง",
  "users.addUser": "เพิ่มผู้ใช้",
  "users.editUser": "แก้ไขผู้ใช้",
  "users.deleteUser": "ลบผู้ใช้",
  "users.userName": "ชื่อผู้ใช้",
  "users.email": "อีเมล",
  "users.role": "บทบาท",
  "users.status": "สถานะ",
  "users.lastLogin": "เข้าสู่ระบบล่าสุด",
  "users.active": "ใช้งาน",
  "users.inactive": "ไม่ได้ใช้งาน",
  "users.suspended": "ระงับ",
  "users.userCreated": "สร้างผู้ใช้เรียบร้อย",
  "users.userUpdated": "อัปเดตผู้ใช้เรียบร้อย",
  "users.userDeleted": "ลบผู้ใช้เรียบร้อย",
  "users.resetPassword": "รีเซ็ตรหัสผ่าน",
  "users.sendInvite": "ส่งคำเชิญ",
  "users.department": "แผนก",
  "users.position": "ตำแหน่ง",
  "users.searchPlaceholder": "ค้นหาด้วยชื่อ, อีเมล...",
  "users.allRoles": "ทุกบทบาท",
  "users.allStatuses": "ทุกสถานะ",
  "users.createNewUser": "สร้างผู้ใช้ใหม่",
  "users.createNewUserDesc": "เพิ่มผู้ใช้ใหม่ในระบบ",
  "users.editUserInfo": "แก้ไขข้อมูลผู้ใช้และสิทธิ์",

  // Credit Note Management
  "creditNote.title": "จัดการใบลดหนี้",
  "creditNote.subtitle": "จัดการใบลดหนี้ การคืนเงิน และการปรับปรุงการเรียกเก็บ",
  "creditNote.createCreditNote": "สร้างใบลดหนี้",
  "creditNote.totalCreditNotes": "ใบลดหนี้ทั้งหมด",
  "creditNote.draft": "ร่าง",
  "creditNote.issued": "ออกแล้ว",
  "creditNote.applied": "ใช้แล้ว",
  "creditNote.totalCreditAmount": "ยอดเครดิตรวม",
  "creditNote.creditNoteNumber": "เลขที่ใบลดหนี้",
  "creditNote.invoiceReference": "อ้างอิงใบแจ้งหนี้",
  "creditNote.searchPlaceholder": "ใบลดหนี้, ใบแจ้งหนี้, นักเรียน...",
  "creditNote.allTypes": "ทุกประเภท",
  "creditNote.refund": "คืนเงิน",
  "creditNote.adjustment": "ปรับปรุง",
  "creditNote.cancellation": "ยกเลิก",
  "creditNote.discount": "ส่วนลด",
  "creditNote.showingOf": "แสดง {count} จาก {total} ใบลดหนี้",
  "creditNote.creditNoteDetails": "รายละเอียดใบลดหนี้",
  "creditNote.creditNoteDetailsDesc": "ดูและจัดการข้อมูลใบลดหนี้และรายละเอียดการดำเนินการ",
  "creditNote.studentInfo": "ข้อมูลนักเรียน",
  "creditNote.studentName": "ชื่อนักเรียน",
  "creditNote.parentGuardian": "ผู้ปกครอง",
  "creditNote.creditInfo": "ข้อมูลเครดิต",
  "creditNote.relatedInvoice": "ใบแจ้งหนี้ที่เกี่ยวข้อง",
  "creditNote.originalAmount": "ยอดเดิม",
  "creditNote.creditAmount": "ยอดเครดิต",
  "creditNote.creditDetails": "รายละเอียดเครดิต",
  "creditNote.reason": "เหตุผล",
  "creditNote.appliedDate": "วันที่ใช้",
  "creditNote.processingInfo": "ข้อมูลการดำเนินการ",
  "creditNote.issuedBy": "ออกโดย",
  "creditNote.approvedBy": "อนุมัติโดย",
  "creditNote.notes": "หมายเหตุ",
  "creditNote.sendToParent": "ส่งถึงผู้ปกครอง",
  "creditNote.createNewCreditNote": "สร้างใบลดหนี้ใหม่",
  "creditNote.createNewDesc": "สร้างใบลดหนี้ใหม่สำหรับการคืนเงิน การปรับปรุง หรือการยกเลิก",
  "creditNote.selectInvoice": "เลือกใบแจ้งหนี้",
  "creditNote.selectAnInvoice": "เลือกใบแจ้งหนี้...",
  "creditNote.noInvoicesFound": "ไม่พบใบแจ้งหนี้ กรุณาสร้างใบแจ้งหนี้ก่อน",
  "creditNote.invoiceDetails": "รายละเอียดใบแจ้งหนี้",
  "creditNote.creditType": "ประเภทเครดิต",
  "creditNote.billingAdjustment": "ปรับปรุงการเรียกเก็บ",
  "creditNote.courseCancellation": "ยกเลิกหลักสูตร",
  "creditNote.discountApplied": "ใช้ส่วนลดแล้ว",
  "creditNote.enterReason": "ระบุเหตุผลสำหรับใบลดหนี้",
  "creditNote.additionalNotes": "หมายเหตุเพิ่มเติม",
  "creditNote.enterAdditionalNotes": "ระบุหมายเหตุหรือความคิดเห็นเพิ่มเติม",
  "creditNote.createdSuccess": "สร้างใบลดหนี้ {number} เรียบร้อย",
  "creditNote.downloaded": "ดาวน์โหลดใบลดหนี้ {number} แล้ว",
  "creditNote.sentTo": "ส่งใบลดหนี้ถึง {name} แล้ว",
  "creditNote.selectInvoiceAndFill": "กรุณาเลือกใบแจ้งหนี้และกรอกข้อมูลที่จำเป็น",
  "creditNote.enterValidAmount": "กรุณาระบุยอดเครดิตที่ถูกต้อง",
  "creditNote.cannotExceed": "ยอดเครดิตไม่สามารถเกินยอดใบแจ้งหนี้เดิม",
  "creditNote.showEntries": "แสดง",
  "creditNote.entries": "รายการ",

  // Invoice Email Management
  "invoiceEmail.title": "จัดการอีเมลใบแจ้งหนี้",
  "invoiceEmail.subtitle": "ส่งอีเมลใบแจ้งหนี้ถึงผู้ปกครองพร้อมเทมเพลตอัตโนมัติและติดตามการส่ง",
  "invoiceEmail.sendEmails": "ส่งอีเมล",
  "invoiceEmail.emailJobs": "งานส่งอีเมล",
  "invoiceEmail.sendingOptions": "ตัวเลือกการส่งอีเมล",
  "invoiceEmail.sendAll": "ส่งทั้งหมด",
  "invoiceEmail.sendAllDesc": "ส่งถึงนักเรียนทุกคนในระบบ",
  "invoiceEmail.batchSend": "ส่งเป็นกลุ่ม",
  "invoiceEmail.batchSendDesc": "ส่งถึงกลุ่มที่กรอง",
  "invoiceEmail.individualSend": "ส่งรายบุคคล",
  "invoiceEmail.individualSendDesc": "ส่งถึงนักเรียนที่เลือก",
  "invoiceEmail.students": "นักเรียน",
  "invoiceEmail.selected": "ที่เลือก",
  "invoiceEmail.filterCriteria": "เงื่อนไขการกรอง",
  "invoiceEmail.grades": "ชั้นเรียน",
  "invoiceEmail.studentStatus": "สถานะนักเรียน",
  "invoiceEmail.applyFilters": "ใช้ตัวกรอง",
  "invoiceEmail.selectStudents": "เลือกนักเรียน",
  "invoiceEmail.searchPlaceholder": "ค้นหาด้วยชื่อ, รหัสนักเรียน, รหัสครอบครัว...",
  "invoiceEmail.selectedStudents": "นักเรียนที่เลือก",
  "invoiceEmail.emailTemplate": "เทมเพลตอีเมล",
  "invoiceEmail.previewEmail": "ดูตัวอย่างอีเมล",
  "invoiceEmail.sendControls": "การควบคุมการส่ง",
  "invoiceEmail.recipients": "ผู้รับ",
  "invoiceEmail.template": "เทมเพลต",
  "invoiceEmail.estimatedTime": "เวลาโดยประมาณ",
  "invoiceEmail.minutes": "นาที",
  "invoiceEmail.sendingEmails": "กำลังส่งอีเมล...",
  "invoiceEmail.sendEmails2": "ส่ง {count} อีเมล",
  "invoiceEmail.sendingEmailsBtn": "กำลังส่งอีเมล...",
  "invoiceEmail.emailHistory": "ประวัติการส่งอีเมล",
  "invoiceEmail.jobName": "ชื่องาน",
  "invoiceEmail.progress": "ความคืบหน้า",
  "invoiceEmail.created": "สร้างเมื่อ",
  "invoiceEmail.createdBy": "สร้างโดย",
  "invoiceEmail.emailPreview": "ตัวอย่างอีเมล",
  "invoiceEmail.previewDesc": "ดูตัวอย่างอีเมลที่ผู้ปกครองจะได้รับ",
  "invoiceEmail.selectStudent": "เลือกนักเรียน",
  "invoiceEmail.to": "ถึง",
  "invoiceEmail.subject": "หัวเรื่อง",
  "invoiceEmail.message": "ข้อความ",
  "invoiceEmail.footer": "ส่วนท้าย",
  "invoiceEmail.attachment": "ไฟล์แนบ",
  "invoiceEmail.noStudentsPreview": "ไม่มีนักเรียนสำหรับดูตัวอย่าง",
  "invoiceEmail.selectRecipients": "กรุณาเลือกผู้รับก่อนส่ง",
  "invoiceEmail.emailsSent": "ส่งอีเมลสำเร็จ! ส่งแล้ว {sent} ล้มเหลว {failed}",
  "invoiceEmail.sent": "ส่งแล้ว",
  "invoiceEmail.failed": "ล้มเหลว",
  "invoiceEmail.pending": "รอดำเนินการ",
  "invoiceEmail.running": "กำลังทำงาน",
  "invoiceEmail.completed": "เสร็จสิ้น",
  "invoiceEmail.cancelled": "ยกเลิก",
  "invoiceEmail.default": "ค่าเริ่มต้น",

  // Invoice Overview
  "invoiceOverview.title": "ภาพรวมใบแจ้งหนี้",
  "invoiceOverview.subtitle": "จัดการใบแจ้งหนี้ทั้งหมดและติดตามสถานะการชำระ",
  "invoiceOverview.totalInvoices": "ใบแจ้งหนี้ทั้งหมด",
  "invoiceOverview.paidInvoices": "ชำระแล้ว",
  "invoiceOverview.unpaidInvoices": "ยังไม่ชำระ",
  "invoiceOverview.overdueInvoices": "เกินกำหนด",
  "invoiceOverview.totalValue": "มูลค่ารวม",
  "invoiceOverview.ofTotal": "ของทั้งหมด",
  "invoiceOverview.searchFilter": "ค้นหาและกรอง",
  "invoiceOverview.searchPlaceholder": "ใบแจ้งหนี้, นักเรียน, ผู้ปกครอง...",
  "invoiceOverview.noInvoicesYet": "ยังไม่มีใบแจ้งหนี้",
  "invoiceOverview.noInvoicesDescription": "ใบแจ้งหนี้ที่สร้างจากหน้า \"สร้างใบแจ้งหนี้\" จะแสดงที่นี่ ไปที่ จัดการใบแจ้งหนี้ → สร้างใบแจ้งหนี้ เพื่อสร้างใบแจ้งหนี้ใหม่",
  "invoiceOverview.showing": "แสดง",
  "invoiceOverview.of": "จาก",
  "invoiceOverview.invoices": "รายการ",
  "invoiceOverview.filteredFrom": "กรองจาก",
  "invoiceOverview.total": "ทั้งหมด",
  "invoiceOverview.page": "หน้า",
  "invoiceOverview.goToPage": "ไปหน้า",
  "invoiceOverview.daysOverdue": "วันที่เกินกำหนด",
  "invoiceOverview.daysLeft": "วันที่เหลือ",
  "invoiceOverview.daysRemaining": "วันที่เหลือ",
  "invoiceOverview.sent": "ส่งแล้ว",
  "invoiceOverview.viewDetails": "ดูรายละเอียด",
  "invoiceOverview.downloadInvoice": "ดาวน์โหลดใบแจ้งหนี้",
  "invoiceOverview.sendReminder": "ส่งการแจ้งเตือน",
  "invoiceOverview.invoiceDetails": "รายละเอียดใบแจ้งหนี้",
  "invoiceOverview.viewInvoiceInfo": "ดูข้อมูลใบแจ้งหนี้, สถานะการชำระ และส่งการแจ้งเตือน",
  "invoiceOverview.studentInfo": "ข้อมูลนักเรียน",
  "invoiceOverview.fullName": "ชื่อ-นามสกุล",
  "invoiceOverview.financialDetails": "รายละเอียดการเงิน",
  "invoiceOverview.amountDue": "ยอดที่ต้องชำระ",
  "invoiceOverview.academicTerm": "ภาคเรียน",
  "invoiceOverview.importantDates": "วันที่สำคัญ",
  "invoiceOverview.communicationHistory": "ประวัติการติดต่อ",
  "invoiceOverview.paymentRemindersSent": "การแจ้งเตือนที่ส่ง",
  "invoiceOverview.totalRemindersDescription": "จำนวนการแจ้งเตือนที่ส่งถึงผู้ปกครอง",
  "invoiceOverview.reminderSent": "ส่งการแจ้งเตือนถึงผู้ปกครองของ {name} แล้ว",
  "invoiceOverview.invoiceDownloaded": "ดาวน์โหลดใบแจ้งหนี้ {number} แล้ว",
  "invoiceOverview.listRefreshed": "รีเฟรชรายการใบแจ้งหนี้แล้ว",
  "invoiceOverview.downloadSuccess": "ดาวน์โหลดใบแจ้งหนี้เรียบร้อย",
  "invoiceOverview.yearly": "รายปี",
  "invoiceOverview.termly": "รายเทอม",
  "invoiceOverview.channel": "ช่องทาง",
  "invoiceOverview.reminders": "การแจ้งเตือน",
  "invoiceOverview.type": "ประเภท",

  // School Info
  "school.name": "โรงเรียนนานาชาติคิงส์คอลเลจ กรุงเทพฯ",
  "school.address": "99/1 หมู่ 5 ซอยเสรีไทย 35 คันนายาว กรุงเทพฯ 10230",
  "school.phone": "+66 2 138 5455",
  "school.email": "admissions@kingsbangkok.ac.th",
  "school.website": "www.kingsbangkok.ac.th",
  "school.taxId": "0105559012345",
}

const translations: Record<Language, Record<string, string>> = { en, th }

const LANGUAGE_STORAGE_KEY = 'app-language'

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage or default to 'en'
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY)
      if (saved === 'en' || saved === 'th') {
        return saved
      }
    }
    return 'en'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Export for direct access if needed
export { translations, type Language }
